// es = Spanish, en = English, pr = pronunciation for English speakers (CAPS = stressed syllable), note = optional tip
// kind: omitted = something you say, "hear" = something they'll say to you, "word" = a single vocabulary word
const CATEGORIES = [
  { id: "daily", name: "Everyday", short: "Daily", es: "Diario", icon: "👋", topics: [
    { id: "greet", name: "Hellos & goodbyes", es: "Saludos", icon: "👋" },
    { id: "polite", name: "Please, thanks, sorry", es: "Cortesía", icon: "🙏" },
    { id: "understand", name: "Understanding each other", es: "No entiendo", icon: "🤔" },
    { id: "directions", name: "Directions", es: "Direcciones", icon: "🧭" },
    { id: "help", name: "Help & odds and ends", es: "Ayuda", icon: "🙋" },
    { id: "casual", name: "Casual Mexican", es: "Coloquial", icon: "😎" },
  ] },
  { id: "food", name: "Restaurant", short: "Food", es: "Restaurante", icon: "🌮", topics: [
    { id: "seat", name: "Getting a table", es: "La mesa", icon: "🪑" },
    { id: "order", name: "Ordering", es: "Pedir", icon: "📝" },
    { id: "custom", name: "Spicy, allergies & diet", es: "Picante y alergias", icon: "🌶️" },
    { id: "drinks", name: "Drinks", es: "Bebidas", icon: "🍺" },
    { id: "meal", name: "During the meal", es: "Durante la comida", icon: "🍽️" },
    { id: "pay", name: "Paying the check", es: "La cuenta", icon: "💳" },
  ] },
  { id: "store", name: "Store", es: "Tienda", icon: "🛍️", topics: [
    { id: "find", name: "Finding things", es: "Buscar", icon: "🔍" },
    { id: "price", name: "Prices & haggling", es: "Precios", icon: "🏷️" },
    { id: "sizes", name: "Sizes & colors", es: "Tallas", icon: "👕" },
    { id: "pay", name: "Paying & change", es: "Pagar", icon: "💵" },
    { id: "register", name: "At the register", es: "En la caja", icon: "🧾" },
    { id: "errands", name: "Market, pharmacy & errands", es: "Mandados", icon: "🧺" },
  ] },
  { id: "garden", name: "Garden", es: "Vivero", icon: "🌱", topics: [
    { id: "water", name: "Water requirements", es: "Riego", icon: "💧" },
    { id: "light", name: "Light requirements", es: "Luz y sol", icon: "☀️" },
    { id: "soil", name: "Soil & fertilizer", es: "Tierra y abono", icon: "🟫" },
    { id: "pots", name: "Pots & planting", es: "Macetas", icon: "🪴" },
    { id: "size", name: "Size & growth", es: "Tamaño", icon: "📏" },
    { id: "climate", name: "Heat, wind & sea air", es: "Clima", icon: "🌊" },
    { id: "pests", name: "Pests & problems", es: "Plagas", icon: "🐛" },
    { id: "safety", name: "Pets & kids", es: "Mascotas y niños", icon: "🐶" },
    { id: "bloom", name: "Flowers & fruit", es: "Flores y frutos", icon: "🌺" },
    { id: "find", name: "Finding a plant", es: "Buscar plantas", icon: "🔍" },
    { id: "buy", name: "Buying & delivery", es: "Compra y entrega", icon: "🚚" },
    { id: "tools", name: "Tools & supplies", es: "Herramientas", icon: "🧤" },
    { id: "kinds", name: "Kinds of plants", es: "Tipos de plantas", icon: "🌴" },
  ] },
  { id: "gas", name: "Gas station", short: "Gas", es: "Gasolinera", icon: "⛽", topics: [
    { id: "fill", name: "Filling up", es: "Cargar gasolina", icon: "⛽" },
    { id: "pay", name: "Paying & avoiding scams", es: "Pagar sin trampas", icon: "💵" },
    { id: "service", name: "Air, oil & windshield", es: "Aire y aceite", icon: "🛞" },
    { id: "trouble", name: "Car trouble", es: "Problemas con el coche", icon: "🔧" },
    { id: "road", name: "The road ahead", es: "La carretera", icon: "🛣️" },
    { id: "stop", name: "Restroom & snacks", es: "Baño y tienda", icon: "🚻" },
    { id: "car", name: "Car words", es: "Partes del coche", icon: "🚗" },
  ] },
  { id: "pharmacy", name: "Pharmacy", short: "Meds", es: "Farmacia", icon: "💊", topics: [
    { id: "symptoms", name: "Saying what's wrong", es: "Síntomas", icon: "🤒" },
    { id: "ask", name: "Asking for medicine", es: "Pedir medicina", icon: "💊" },
    { id: "dose", name: "How to take it", es: "Cómo tomarlo", icon: "⏰" },
    { id: "rx", name: "Prescriptions & the doctor", es: "Receta y consultorio", icon: "🩺" },
    { id: "beach", name: "Sun, bites & stomach", es: "Sol, piquetes y estómago", icon: "🏖️" },
    { id: "urgent", name: "Emergencies", es: "Urgencias", icon: "🚑" },
    { id: "words", name: "Body & medicine words", es: "Cuerpo y medicinas", icon: "🦴" },
  ] },
  { id: "clean", name: "House cleaning", short: "Clean", es: "Limpieza", icon: "🧹", topics: [
    { id: "schedule", name: "Days, hours & pay", es: "Horario y pago", icon: "📅" },
    { id: "tasks", name: "What to clean today", es: "Qué limpiar", icon: "🧽" },
    { id: "laundry", name: "Laundry & beds", es: "Ropa y camas", icon: "🧺" },
    { id: "kitchen", name: "Kitchen & dishes", es: "Cocina y trastes", icon: "🍽️" },
    { id: "careful", name: "Please be careful with…", es: "Cuidado con…", icon: "⚠️" },
    { id: "supplies", name: "Supplies", es: "Productos de limpieza", icon: "🧴" },
    { id: "chat", name: "Thanks & small talk", es: "Plática", icon: "☕" },
  ] },
];

const PHRASES = [
  // ---------- Everyday ----------
  { cat: "daily", topic: "greet", es: "Hola", en: "Hello", pr: "OH-lah" },
  { cat: "daily", topic: "greet", es: "Buenos días", en: "Good morning", pr: "BWEH-nohs DEE-ahs", note: "Use until about noon. Greeting people when you walk into a small shop or elevator is expected." },
  { cat: "daily", topic: "greet", es: "Buenas tardes", en: "Good afternoon", pr: "BWEH-nahs TAR-dehs", note: "From noon until dark." },
  { cat: "daily", topic: "greet", es: "Buenas noches", en: "Good evening / Good night", pr: "BWEH-nahs NOH-chehs", note: "Used both as a greeting after dark and as goodbye." },
  { cat: "daily", topic: "greet", es: "¿Qué tal?", en: "How's it going?", pr: "keh TAHL" },
  { cat: "daily", topic: "greet", es: "¿Cómo está?", en: "How are you? (polite)", pr: "KOH-moh ehs-TAH", note: "Formal \"usted\" form. Use it with strangers, older people and staff." },
  { cat: "daily", topic: "greet", es: "¿Cómo estás?", en: "How are you? (casual)", pr: "KOH-moh ehs-TAHS", note: "Informal \"tú\" form, for friends and people your age." },
  { cat: "daily", topic: "greet", es: "Bien, gracias. ¿Y usted?", en: "Good, thanks. And you?", pr: "bee-EHN GRAH-see-ahs. ee oos-TEHD" },
  { cat: "daily", topic: "greet", es: "Mucho gusto", en: "Nice to meet you", pr: "MOO-choh GOOS-toh" },
  { cat: "daily", topic: "greet", es: "Me llamo…", en: "My name is…", pr: "meh YAH-moh" },
  { cat: "daily", topic: "polite", es: "Por favor", en: "Please", pr: "por fah-VOR" },
  { cat: "daily", topic: "polite", es: "Muchas gracias", en: "Thank you very much", pr: "MOO-chahs GRAH-see-ahs" },
  { cat: "daily", topic: "polite", es: "De nada", en: "You're welcome", pr: "deh NAH-dah", note: "You'll also hear \"a la orden\" (at your service) and \"para servirle\"." },
  { cat: "daily", topic: "polite", es: "Con permiso", en: "Excuse me (to get past someone)", pr: "kohn pehr-MEE-soh", note: "Also said when leaving a table or a room." },
  { cat: "daily", topic: "polite", es: "Disculpe", en: "Excuse me / Sorry (to get attention)", pr: "dees-KOOL-peh" },
  { cat: "daily", topic: "polite", es: "Perdón", en: "Sorry / Pardon me", pr: "pehr-DOHN" },
  { cat: "daily", topic: "polite", es: "¿Mande?", en: "Pardon? / Sorry, what?", pr: "MAHN-deh", note: "The polite Mexican way to ask someone to repeat. Much nicer than \"¿Qué?\"." },
  { cat: "daily", topic: "casual", es: "Sale", en: "OK / Deal (casual)", pr: "SAH-leh", note: "Very Mexican. \"Va\" and \"órale\" work the same way." },
  { cat: "daily", topic: "understand", es: "No entiendo", en: "I don't understand", pr: "noh ehn-tee-EHN-doh" },
  { cat: "daily", topic: "understand", es: "¿Habla inglés?", en: "Do you speak English?", pr: "AH-blah een-GLEHS" },
  { cat: "daily", topic: "understand", es: "Hablo un poco de español", en: "I speak a little Spanish", pr: "AH-bloh oon POH-koh deh ehs-pah-NYOHL" },
  { cat: "daily", topic: "understand", es: "¿Puede hablar más despacio?", en: "Can you speak more slowly?", pr: "PWEH-deh ah-BLAR mahs dehs-PAH-see-oh" },
  { cat: "daily", topic: "understand", es: "¿Cómo se dice … en español?", en: "How do you say … in Spanish?", pr: "KOH-moh seh DEE-seh … ehn ehs-pah-NYOHL" },
  { cat: "daily", topic: "directions", es: "¿Dónde está el baño?", en: "Where is the bathroom?", pr: "DOHN-deh ehs-TAH ehl BAH-nyoh", note: "Public restrooms often cost 5–10 pesos. Keep coins handy." },
  { cat: "daily", topic: "directions", es: "¿Dónde está…?", en: "Where is…?", pr: "DOHN-deh ehs-TAH" },
  { cat: "daily", topic: "directions", es: "¿Está lejos?", en: "Is it far?", pr: "ehs-TAH LEH-hohs" },
  { cat: "daily", topic: "directions", es: "A la derecha / a la izquierda", en: "To the right / to the left", pr: "ah lah deh-REH-chah / ah lah ees-kee-EHR-dah" },
  { cat: "daily", topic: "directions", es: "Todo derecho", en: "Straight ahead", pr: "TOH-doh deh-REH-choh" },
  { cat: "daily", topic: "directions", es: "¿Cuánto cuesta ir a…?", en: "How much to go to…? (taxi)", pr: "KWAHN-toh KWEHS-tah eer ah", note: "Agree on the fare before you get in if there's no meter." },
  { cat: "daily", topic: "help", es: "¿Qué hora es?", en: "What time is it?", pr: "keh OH-rah ehs" },
  { cat: "daily", topic: "help", es: "Ahorita", en: "Right now / In a little bit", pr: "ah-oh-REE-tah", note: "Famously flexible: can mean this second, in an hour, or maybe never." },
  { cat: "daily", topic: "help", es: "¿Me puede ayudar?", en: "Can you help me?", pr: "meh PWEH-deh ah-yoo-DAR" },
  { cat: "daily", topic: "help", es: "Estoy perdido / perdida", en: "I'm lost (man / woman)", pr: "ehs-TOY pehr-DEE-doh / pehr-DEE-dah" },
  { cat: "daily", topic: "help", es: "¿Hay wifi? ¿Cuál es la contraseña?", en: "Is there wifi? What's the password?", pr: "eye WEE-fee? kwahl ehs lah kohn-trah-SEH-nyah" },
  { cat: "daily", topic: "help", es: "¿Nos puede tomar una foto?", en: "Could you take a photo of us?", pr: "nohs PWEH-deh toh-MAR OO-nah FOH-toh" },
  { cat: "daily", topic: "help", es: "No hay problema", en: "No problem", pr: "noh eye proh-BLEH-mah" },
  { cat: "daily", topic: "casual", es: "¿Qué onda?", en: "What's up? (casual)", pr: "keh OHN-dah" },
  { cat: "daily", topic: "casual", es: "¡Qué padre!", en: "How cool! / Awesome!", pr: "keh PAH-dreh" },
  { cat: "daily", topic: "greet", es: "Nos vemos", en: "See you", pr: "nohs VEH-mohs" },
  { cat: "daily", topic: "greet", es: "Hasta luego", en: "See you later / Bye", pr: "AHS-tah LWEH-goh" },
  { cat: "daily", topic: "greet", es: "¡Que le vaya bien!", en: "Have a good one! (lit. may it go well)", pr: "keh leh VAH-yah bee-EHN" },

  // ---------- Restaurants ----------
  { cat: "food", topic: "seat", es: "Una mesa para dos, por favor", en: "A table for two, please", pr: "OO-nah MEH-sah PAH-rah dohs, por fah-VOR", note: "tres = 3, cuatro = 4, cinco = 5" },
  { cat: "food", topic: "seat", es: "Tengo una reservación a nombre de…", en: "I have a reservation under the name…", pr: "TEHN-goh OO-nah reh-sehr-vah-see-OHN ah NOHM-breh deh" },
  { cat: "food", topic: "seat", es: "¿Tiene mesa afuera?", en: "Do you have a table outside?", pr: "tee-EH-neh MEH-sah ah-FWEH-rah" },
  { cat: "food", topic: "seat", es: "La carta, por favor", en: "The menu, please", pr: "lah KAR-tah, por fah-VOR", note: "\"El menú\" is also understood. \"Menú del día\" / \"comida corrida\" is a cheap set lunch." },
  { cat: "food", topic: "seat", es: "Joven / Señorita", en: "Excuse me (to call the waiter / waitress)", pr: "HOH-vehn / seh-nyoh-REE-tah", note: "\"Joven\" (young man) is used for male servers of any age. Never snap or whistle." },
  { cat: "food", topic: "order", es: "¿Qué me recomienda?", en: "What do you recommend?", pr: "keh meh reh-koh-mee-EHN-dah" },
  { cat: "food", topic: "order", es: "¿Cuál es la especialidad de la casa?", en: "What's the house specialty?", pr: "kwahl ehs lah ehs-peh-see-ah-lee-DAHD deh lah KAH-sah" },
  { cat: "food", topic: "order", es: "Quisiera…", en: "I would like…", pr: "kee-see-EH-rah" },
  { cat: "food", topic: "order", es: "Me da…, por favor", en: "I'll have…, please (lit. give me)", pr: "meh DAH…, por fah-VOR", note: "Sounds blunt in English but is completely normal and polite in Mexico." },
  { cat: "food", topic: "order", es: "¿Me regala una servilleta?", en: "Could I get a napkin?", pr: "meh reh-GAH-lah OO-nah sehr-vee-YEH-tah", note: "\"Regalar\" literally means to gift, but Mexicans use it as a soft, polite \"may I have\"." },
  { cat: "food", topic: "order", es: "¿Me trae…?", en: "Could you bring me…?", pr: "meh TRAH-eh" },
  { cat: "food", topic: "order", es: "Para mí…", en: "For me…", pr: "PAH-rah MEE" },
  { cat: "food", topic: "order", es: "Para aquí", en: "For here (dine in)", pr: "PAH-rah ah-KEE" },
  { cat: "food", topic: "order", es: "Para llevar", en: "To go", pr: "PAH-rah yeh-VAR" },
  { cat: "food", topic: "order", es: "¿De qué tiene?", en: "What fillings do you have? (tacos, tamales…)", pr: "deh KEH tee-EH-neh" },
  { cat: "food", topic: "order", es: "Dos tacos al pastor, por favor", en: "Two al pastor tacos, please", pr: "dohs TAH-kohs ahl pahs-TOR", note: "Al pastor = spit-roasted marinated pork, often with pineapple." },
  { cat: "food", topic: "custom", es: "Con todo", en: "With everything", pr: "kohn TOH-doh", note: "On tacos this usually means onion and cilantro." },
  { cat: "food", topic: "custom", es: "Sin cebolla", en: "Without onion", pr: "seen seh-BOH-yah" },
  { cat: "food", topic: "custom", es: "¿Pica?", en: "Is it spicy?", pr: "PEE-kah", note: "If they say \"poquito\" (a little), assume it's spicy." },
  { cat: "food", topic: "custom", es: "Que no pique, por favor", en: "Not spicy, please", pr: "keh noh PEE-keh, por fah-VOR" },
  { cat: "food", topic: "custom", es: "La salsa aparte, por favor", en: "Sauce on the side, please", pr: "lah SAHL-sah ah-PAR-teh" },
  { cat: "food", topic: "custom", es: "Soy alérgico / alérgica a…", en: "I'm allergic to… (man / woman)", pr: "soy ah-LEHR-hee-koh / ah-LEHR-hee-kah ah", note: "cacahuate = peanut, mariscos = shellfish, nueces = nuts, lácteos = dairy, gluten = gluten" },
  { cat: "food", topic: "custom", es: "Soy vegetariano / vegetariana", en: "I'm vegetarian (man / woman)", pr: "soy veh-heh-tah-ree-AH-noh" },
  { cat: "food", topic: "custom", es: "¿Tiene carne?", en: "Does it have meat?", pr: "tee-EH-neh KAR-neh", note: "Some people don't count chicken or ham as \"carne\". Ask about each: pollo, jamón, manteca (lard)." },
  { cat: "food", topic: "custom", es: "¿Las quesadillas llevan queso?", en: "Do the quesadillas come with cheese?", pr: "lahs keh-sah-DEE-yahs YEH-vahn KEH-soh", note: "In Mexico City they often don't unless you ask!" },
  { cat: "food", topic: "drinks", es: "Una cerveza, por favor", en: "A beer, please", pr: "OO-nah sehr-VEH-sah", note: "Ask \"¿Cuáles tiene?\" to hear what beers they have." },
  { cat: "food", topic: "drinks", es: "Una michelada", en: "A michelada (beer with lime and salt, often spicy sauces)", pr: "OO-nah mee-cheh-LAH-dah", note: "A \"chelada\" is just beer, lime and salt, with no sauces." },
  { cat: "food", topic: "drinks", es: "Un agua natural", en: "A still water", pr: "oon AH-gwah nah-too-RAHL", note: "\"Agua mineral\" is sparkling. \"Agua fresca\" is a fruit drink (jamaica, horchata, tamarindo)." },
  { cat: "food", topic: "drinks", es: "¿El agua es purificada?", en: "Is the water purified?", pr: "ehl AH-gwah ehs poo-ree-fee-KAH-dah", note: "Don't drink tap water. Restaurant ice is normally made from purified water." },
  { cat: "food", topic: "drinks", es: "Sin hielo", en: "No ice", pr: "seen YEH-loh" },
  { cat: "food", topic: "drinks", es: "Un café con leche", en: "A coffee with milk", pr: "oon kah-FEH kohn LEH-cheh", note: "\"Café de olla\" is sweet, cinnamon-spiced coffee. Worth trying." },
  { cat: "food", topic: "drinks", es: "Otra, por favor", en: "Another one, please", pr: "OH-trah, por fah-VOR", note: "Use \"otro\" for a masculine thing (otro café, otro taco)." },
  { cat: "food", topic: "meal", es: "Todo bien, gracias", en: "Everything's good, thanks", pr: "TOH-doh bee-EHN, GRAH-see-ahs" },
  { cat: "food", topic: "meal", es: "¡Está muy rico!", en: "It's delicious!", pr: "ehs-TAH mooy REE-koh" },
  { cat: "food", topic: "meal", es: "¡Provecho!", en: "Enjoy your meal!", pr: "proh-VEH-choh", note: "Mexicans say it to other diners when passing their table or leaving the restaurant." },
  { cat: "food", topic: "pay", es: "La cuenta, por favor", en: "The check, please", pr: "lah KWEHN-tah, por fah-VOR", note: "It won't come until you ask. You can also mime signing in the air." },
  { cat: "food", topic: "pay", es: "¿Aceptan tarjeta?", en: "Do you take cards?", pr: "ah-SEHP-tahn tar-HEH-tah", note: "Many taquerías and markets are cash only." },
  { cat: "food", topic: "pay", es: "¿Me trae la terminal?", en: "Can you bring the card machine?", pr: "meh TRAH-eh lah tehr-mee-NAHL", note: "The card reader comes to your table. Your card shouldn't leave your sight." },
  { cat: "food", topic: "pay", es: "¿Está incluida la propina?", en: "Is the tip included?", pr: "ehs-TAH een-kloo-EE-dah lah proh-PEE-nah", note: "10–15% is standard at sit-down restaurants. Check the bill for \"servicio incluido\"." },
  { cat: "food", topic: "pay", es: "¿Podemos pagar por separado?", en: "Can we pay separately?", pr: "poh-DEH-mohs pah-GAR por seh-pah-RAH-doh" },
  { cat: "food", topic: "pay", es: "¿Dónde se paga?", en: "Where do I pay?", pr: "DOHN-deh seh PAH-gah", note: "At street stalls you usually pay at the end. Tell them what you ate." },

  // ---------- Stores ----------
  { cat: "store", topic: "price", es: "¿Cuánto cuesta?", en: "How much does it cost?", pr: "KWAHN-toh KWEHS-tah" },
  { cat: "store", topic: "price", es: "¿Cuánto es?", en: "How much is it? (total)", pr: "KWAHN-toh EHS" },
  { cat: "store", topic: "price", es: "¿Cuánto le debo?", en: "What do I owe you?", pr: "KWAHN-toh leh DEH-boh" },
  { cat: "store", topic: "price", kind: "hear", es: "Son ciento cincuenta pesos", en: "That's 150 pesos", pr: "sohn see-EHN-toh seen-KWEHN-tah PEH-sohs", note: "20 veinte · 50 cincuenta · 100 cien · 200 doscientos · 500 quinientos · 1,000 mil" },
  { cat: "store", topic: "find", es: "¿Tiene…?", en: "Do you have…?", pr: "tee-EH-neh" },
  { cat: "store", topic: "find", es: "Estoy buscando…", en: "I'm looking for…", pr: "ehs-TOY boos-KAHN-doh" },
  { cat: "store", topic: "find", es: "¿Dónde encuentro…?", en: "Where can I find…?", pr: "DOHN-deh ehn-KWEHN-troh" },
  { cat: "store", topic: "find", es: "Solo estoy viendo, gracias", en: "I'm just looking, thanks", pr: "SOH-loh ehs-TOY vee-EHN-doh, GRAH-see-ahs" },
  { cat: "store", topic: "sizes", es: "¿Me lo puedo probar?", en: "Can I try it on?", pr: "meh loh PWEH-doh proh-BAR" },
  { cat: "store", topic: "sizes", es: "¿Tiene otra talla?", en: "Do you have another size?", pr: "tee-EH-neh OH-trah TAH-yah" },
  { cat: "store", topic: "sizes", es: "Más grande / más chico", en: "Bigger / smaller", pr: "mahs GRAHN-deh / mahs CHEE-koh", note: "Mexico says \"chico\" far more than \"pequeño\"." },
  { cat: "store", topic: "sizes", es: "¿Lo tiene en otro color?", en: "Do you have it in another color?", pr: "loh tee-EH-neh ehn OH-troh koh-LOR" },
  { cat: "store", topic: "sizes", es: "Me lo llevo", en: "I'll take it", pr: "meh loh YEH-voh", note: "\"Me la llevo\" for a feminine thing (la camisa, la bolsa)." },
  { cat: "store", topic: "price", es: "Está muy caro", en: "It's very expensive", pr: "ehs-TAH mooy KAH-roh" },
  { cat: "store", topic: "price", es: "¿Me hace un descuento?", en: "Can you give me a discount?", pr: "meh AH-seh oon dehs-KWEHN-toh", note: "Fine at markets and with street vendors. Not in chain stores or supermarkets." },
  { cat: "store", topic: "price", es: "¿Es lo menos?", en: "Is that your best price?", pr: "ehs loh MEH-nohs", note: "The classic market bargaining line. Keep it friendly." },
  { cat: "store", topic: "pay", es: "¿Puedo pagar con tarjeta?", en: "Can I pay by card?", pr: "PWEH-doh pah-GAR kohn tar-HEH-tah" },
  { cat: "store", topic: "pay", kind: "hear", es: "Solo efectivo", en: "Cash only", pr: "SOH-loh eh-fehk-TEE-voh", note: "A sign you'll see often." },
  { cat: "store", topic: "pay", es: "¿Aceptan dólares?", en: "Do you accept dollars?", pr: "ah-SEHP-tahn DOH-lah-rehs", note: "Paying in pesos almost always gets you a better rate." },
  { cat: "store", topic: "pay", es: "¿Tiene cambio de quinientos?", en: "Do you have change for a 500?", pr: "tee-EH-neh KAHM-bee-oh deh kee-nee-EHN-tohs", note: "Small shops and taxis often can't break big bills. Carry 20s, 50s and coins." },
  { cat: "store", topic: "pay", es: "No traigo cambio", en: "I don't have change / small bills", pr: "noh TRY-goh KAHM-bee-oh", note: "You'll also hear \"feria\", Mexican slang for small change." },
  { cat: "store", topic: "register", es: "¿Me cobra, por favor?", en: "Can you ring me up, please?", pr: "meh KOH-brah, por fah-VOR" },
  { cat: "store", topic: "register", kind: "hear", es: "¿Algo más?", en: "Anything else?", pr: "AHL-goh MAHS", note: "You'll hear this at every register." },
  { cat: "store", topic: "register", es: "Es todo, gracias", en: "That's all, thanks", pr: "ehs TOH-doh, GRAH-see-ahs" },
  { cat: "store", topic: "register", kind: "hear", es: "¿Redondea?", en: "Would you like to round up? (to donate)", pr: "reh-dohn-DEH-ah", note: "Cashiers at OXXO and supermarkets ask this. \"No, gracias\" is perfectly fine." },
  { cat: "store", topic: "register", es: "¿Me da una bolsa?", en: "Can I have a bag?", pr: "meh DAH OO-nah BOHL-sah", note: "Many states ban free plastic bags, so bring your own tote." },
  { cat: "store", topic: "register", es: "No necesito bolsa, gracias", en: "I don't need a bag, thanks", pr: "noh neh-seh-SEE-toh BOHL-sah" },
  { cat: "store", topic: "register", es: "¿Me da el ticket?", en: "Can I have the receipt?", pr: "meh DAH ehl TEE-keht", note: "\"Ticket\" is the everyday word for a receipt." },
  { cat: "store", topic: "errands", es: "Un kilo de…, por favor", en: "A kilo of…, please", pr: "oon KEE-loh deh", note: "Produce and meat are sold by the kilo (about 2.2 lb). \"Medio kilo\" = half, \"un cuarto\" = a quarter." },
  { cat: "store", topic: "errands", es: "¿Está fresco?", en: "Is it fresh?", pr: "ehs-TAH FREHS-koh" },
  { cat: "store", topic: "errands", es: "¿Tiene algo para…?", en: "Do you have something for…? (pharmacy)", pr: "tee-EH-neh AHL-goh PAH-rah", note: "…el dolor de cabeza (headache), …la diarrea, …las quemaduras de sol (sunburn), …la tos (cough)" },
  { cat: "store", topic: "errands", es: "Una recarga de cien pesos, por favor", en: "A 100-peso phone top-up, please", pr: "OO-nah reh-KAR-gah deh see-EHN PEH-sohs", note: "Top up prepaid SIMs (Telcel, AT&T) at any OXXO. Tell them the carrier and your number." },
  { cat: "store", topic: "errands", es: "¿Dónde hay un cajero?", en: "Where is there an ATM?", pr: "DOHN-deh eye oon kah-HEH-roh", note: "Use ATMs inside bank branches. Decline the ATM's own currency conversion." },
  { cat: "store", topic: "errands", es: "¿A qué hora cierran?", en: "What time do you close?", pr: "ah keh OH-rah see-EH-rrahn", note: "\"¿A qué hora abren?\" = What time do you open?" },
  { cat: "store", topic: "errands", es: "¿Me lo envuelve para regalo?", en: "Can you gift-wrap it?", pr: "meh loh ehn-VWEHL-veh PAH-rah reh-GAH-loh" },

  // ---------- Garden center (vivero) ----------
  // Water
  { cat: "garden", topic: "water", es: "¿Cada cuánto se riega?", en: "How often do I water it?", pr: "KAH-dah KWAHN-toh seh ree-EH-gah" },
  { cat: "garden", topic: "water", es: "¿Cuánta agua necesita?", en: "How much water does it need?", pr: "KWAHN-tah AH-gwah neh-seh-SEE-tah" },
  { cat: "garden", topic: "water", es: "¿Necesita mucha agua o poca?", en: "Does it need a lot of water or a little?", pr: "neh-seh-SEE-tah MOO-chah AH-gwah oh POH-kah" },
  { cat: "garden", topic: "water", es: "¿Hay que dejar que se seque la tierra?", en: "Should I let the soil dry out between waterings?", pr: "eye keh deh-HAR keh seh SEH-keh lah tee-EH-rrah" },
  { cat: "garden", topic: "water", es: "¿Aguanta la sequía?", en: "Does it tolerate drought?", pr: "ah-GWAHN-tah lah seh-KEE-ah" },
  { cat: "garden", topic: "water", es: "¿Le gusta la humedad?", en: "Does it like humidity?", pr: "leh GOOS-tah lah oo-meh-DAHD" },
  { cat: "garden", topic: "water", es: "¿Es mejor regar en la mañana o en la tarde?", en: "Is it better to water in the morning or the evening?", pr: "ehs meh-HOR reh-GAR ehn lah mah-NYAH-nah oh ehn lah TAR-deh" },
  { cat: "garden", topic: "water", es: "¿Cuánto riego necesita en temporada de lluvias?", en: "How much watering during the rainy season?", pr: "KWAHN-toh ree-EH-goh neh-seh-SEE-tah ehn tehm-poh-RAH-dah deh YOO-vee-ahs" },
  { cat: "garden", topic: "water", kind: "hear", es: "Riego diario", en: "Water it every day", pr: "ree-EH-goh dee-AH-ree-oh" },
  { cat: "garden", topic: "water", kind: "hear", es: "Cada tercer día", en: "Every other day", pr: "KAH-dah tehr-SEHR DEE-ah", note: "Very common in Mexico. Literally “every third day”, but it means every other day." },
  { cat: "garden", topic: "water", kind: "hear", es: "Una o dos veces por semana", en: "Once or twice a week", pr: "OO-nah oh dohs VEH-sehs por seh-MAH-nah" },
  { cat: "garden", topic: "water", kind: "hear", es: "Cuando la tierra esté seca", en: "When the soil is dry", pr: "KWAHN-doh lah tee-EH-rrah ehs-TEH SEH-kah", note: "Push a finger into the soil. If it's dry a couple of centimeters down, it's time." },
  { cat: "garden", topic: "water", kind: "hear", es: "Poquita agua", en: "Just a little water", pr: "poh-KEE-tah AH-gwah" },
  { cat: "garden", topic: "water", kind: "hear", es: "No la encharque", en: "Don't overwater it / don't let it sit in water", pr: "noh lah ehn-CHAR-keh", note: "Encharcar = to waterlog." },
  { cat: "garden", topic: "water", kind: "hear", es: "Se le pudre la raíz", en: "The roots rot", pr: "seh leh POO-dreh lah rah-EES", note: "What happens with too much water." },
  { cat: "garden", topic: "water", kind: "word", es: "regar", en: "to water", pr: "reh-GAR" },
  { cat: "garden", topic: "water", kind: "word", es: "el riego", en: "watering", pr: "ehl ree-EH-goh" },
  { cat: "garden", topic: "water", kind: "word", es: "seco / húmedo", en: "dry / moist", pr: "SEH-koh / OO-meh-doh" },
  { cat: "garden", topic: "water", kind: "word", es: "el drenaje", en: "drainage", pr: "ehl dreh-NAH-heh" },

  // Light
  { cat: "garden", topic: "light", es: "¿Necesita sol directo?", en: "Does it need direct sun?", pr: "neh-seh-SEE-tah sohl dee-REHK-toh" },
  { cat: "garden", topic: "light", es: "¿Cuántas horas de sol necesita?", en: "How many hours of sun does it need?", pr: "KWAHN-tahs OH-rahs deh sohl neh-seh-SEE-tah" },
  { cat: "garden", topic: "light", es: "¿Aguanta el sol todo el día?", en: "Can it take sun all day?", pr: "ah-GWAHN-tah ehl sohl TOH-doh ehl DEE-ah" },
  { cat: "garden", topic: "light", es: "¿Se puede tener en la sombra?", en: "Can it live in the shade?", pr: "seh PWEH-deh teh-NEHR ehn lah SOHM-brah" },
  { cat: "garden", topic: "light", es: "¿Es de interior o de exterior?", en: "Is it an indoor or outdoor plant?", pr: "ehs deh een-teh-ree-OR oh deh ehks-teh-ree-OR" },
  { cat: "garden", topic: "light", es: "¿Sirve para adentro, con poca luz?", en: "Will it work indoors with little light?", pr: "SEER-veh PAH-rah ah-DEHN-troh, kohn POH-kah loos" },
  { cat: "garden", topic: "light", es: "Donde la quiero poner le da sol de la tarde", en: "Where I want to put it gets afternoon sun", pr: "DOHN-deh lah kee-EH-roh poh-NEHR leh dah sohl deh lah TAR-deh", note: "Swap in “de la mañana” for morning sun." },
  { cat: "garden", topic: "light", kind: "hear", es: "Pleno sol / sol directo", en: "Full sun / direct sun", pr: "PLEH-noh sohl / sohl dee-REHK-toh" },
  { cat: "garden", topic: "light", kind: "hear", es: "Media sombra", en: "Partial shade", pr: "MEH-dee-ah SOHM-brah", note: "Sun for part of the day, or filtered sun under trees." },
  { cat: "garden", topic: "light", kind: "hear", es: "Sombra", en: "Shade", pr: "SOHM-brah" },
  { cat: "garden", topic: "light", kind: "hear", es: "Luz indirecta", en: "Indirect light", pr: "loos een-dee-REHK-tah", note: "Bright room, but out of the sun's direct rays." },
  { cat: "garden", topic: "light", kind: "hear", es: "Nada más sol de la mañana", en: "Morning sun only", pr: "NAH-dah mahs sohl deh lah mah-NYAH-nah" },
  { cat: "garden", topic: "light", kind: "hear", es: "Se quema con el sol", en: "It gets sunburned", pr: "seh KEH-mah kohn ehl sohl" },
  { cat: "garden", topic: "light", kind: "word", es: "el sol", en: "sun", pr: "ehl sohl" },
  { cat: "garden", topic: "light", kind: "word", es: "la sombra", en: "shade", pr: "lah SOHM-brah" },
  { cat: "garden", topic: "light", kind: "word", es: "la luz", en: "light", pr: "lah loos" },
  { cat: "garden", topic: "light", kind: "word", es: "adentro / afuera", en: "inside / outside", pr: "ah-DEHN-troh / ah-FWEH-rah" },

  // Soil & fertilizer
  { cat: "garden", topic: "soil", es: "¿Qué tierra le pongo?", en: "What soil should I use for it?", pr: "keh tee-EH-rrah leh POHN-goh" },
  { cat: "garden", topic: "soil", es: "¿Tiene tierra para macetas?", en: "Do you have potting soil?", pr: "tee-EH-neh tee-EH-rrah PAH-rah mah-SEH-tahs" },
  { cat: "garden", topic: "soil", es: "¿Necesita buen drenaje?", en: "Does it need good drainage?", pr: "neh-seh-SEE-tah bwehn dreh-NAH-heh" },
  { cat: "garden", topic: "soil", es: "¿Qué abono le pongo, y cada cuánto?", en: "What fertilizer should I use, and how often?", pr: "keh ah-BOH-noh leh POHN-goh, ee KAH-dah KWAHN-toh" },
  { cat: "garden", topic: "soil", es: "¿Tiene composta?", en: "Do you have compost?", pr: "tee-EH-neh kohm-POHS-tah" },
  { cat: "garden", topic: "soil", es: "¿Lo vende por bulto o suelto?", en: "Do you sell it by the sack or loose?", pr: "loh VEHN-deh por BOOL-toh oh SWEHL-toh" },
  { cat: "garden", topic: "soil", kind: "hear", es: "Una vez al mes", en: "Once a month", pr: "OO-nah vehs ahl mehs" },
  { cat: "garden", topic: "soil", kind: "hear", es: "Revuélvala con tezontle", en: "Mix it with volcanic gravel", pr: "reh-VWEHL-vah-lah kohn teh-SOHN-tleh" },
  { cat: "garden", topic: "soil", kind: "word", es: "la tierra", en: "soil / dirt", pr: "lah tee-EH-rrah" },
  { cat: "garden", topic: "soil", kind: "word", es: "tierra de hoja", en: "leaf-mold soil", pr: "tee-EH-rrah deh OH-hah", note: "Dark composted-leaf soil sold at almost every Mexican vivero." },
  { cat: "garden", topic: "soil", kind: "word", es: "tierra negra", en: "dark topsoil", pr: "tee-EH-rrah NEH-grah" },
  { cat: "garden", topic: "soil", kind: "word", es: "el tezontle", en: "red volcanic gravel (for drainage)", pr: "ehl teh-SOHN-tleh", note: "Mixed in or layered at the bottom of pots for drainage." },
  { cat: "garden", topic: "soil", kind: "word", es: "el abono / el fertilizante", en: "fertilizer", pr: "ehl ah-BOH-noh / ehl fehr-tee-lee-SAHN-teh" },
  { cat: "garden", topic: "soil", kind: "word", es: "la composta", en: "compost", pr: "lah kohm-POHS-tah" },
  { cat: "garden", topic: "soil", kind: "word", es: "humus de lombriz", en: "worm castings", pr: "OO-moos deh lohm-BREES" },
  { cat: "garden", topic: "soil", kind: "word", es: "la arena", en: "sand", pr: "lah ah-REH-nah" },
  { cat: "garden", topic: "soil", kind: "word", es: "el bulto", en: "sack (of soil etc.)", pr: "ehl BOOL-toh" },

  // Pots & planting
  { cat: "garden", topic: "pots", es: "¿De qué tamaño de maceta la necesita?", en: "What size pot does it need?", pr: "deh keh tah-MAH-nyoh deh mah-SEH-tah lah neh-seh-SEE-tah" },
  { cat: "garden", topic: "pots", es: "¿La maceta tiene hoyo para el drenaje?", en: "Does the pot have a drainage hole?", pr: "lah mah-SEH-tah tee-EH-neh OH-yoh PAH-rah ehl dreh-NAH-heh" },
  { cat: "garden", topic: "pots", es: "¿Hay que trasplantarla?", en: "Does it need to be repotted?", pr: "eye keh trahs-plahn-TAR-lah" },
  { cat: "garden", topic: "pots", es: "¿Me la pueden trasplantar aquí?", en: "Can you repot it for me here?", pr: "meh lah PWEH-dehn trahs-plahn-TAR ah-KEE", note: "Many viveros will, often free if you buy the pot and soil there." },
  { cat: "garden", topic: "pots", es: "¿Se puede sembrar en el suelo?", en: "Can it be planted in the ground?", pr: "seh PWEH-deh sehm-BRAR ehn ehl SWEH-loh" },
  { cat: "garden", topic: "pots", es: "¿A qué distancia se siembran?", en: "How far apart do you plant them?", pr: "ah keh dees-TAHN-see-ah seh see-EHM-brahn" },
  { cat: "garden", topic: "pots", kind: "word", es: "la maceta", en: "pot / planter", pr: "lah mah-SEH-tah" },
  { cat: "garden", topic: "pots", kind: "word", es: "el plato", en: "saucer (under the pot)", pr: "ehl PLAH-toh" },
  { cat: "garden", topic: "pots", kind: "word", es: "de barro", en: "terracotta / clay", pr: "deh BAH-rroh" },
  { cat: "garden", topic: "pots", kind: "word", es: "colgante", en: "hanging", pr: "kohl-GAHN-teh" },
  { cat: "garden", topic: "pots", kind: "word", es: "sembrar / plantar", en: "to plant", pr: "sehm-BRAR / plahn-TAR" },
  { cat: "garden", topic: "pots", kind: "word", es: "trasplantar", en: "to repot / transplant", pr: "trahs-plahn-TAR" },

  // Size & growth
  { cat: "garden", topic: "size", es: "¿Qué tan grande se pone?", en: "How big does it get?", pr: "keh tahn GRAHN-deh seh POH-neh" },
  { cat: "garden", topic: "size", es: "¿Qué tan alta crece?", en: "How tall does it grow?", pr: "keh tahn AHL-tah KREH-seh" },
  { cat: "garden", topic: "size", es: "¿Crece rápido o lento?", en: "Does it grow fast or slow?", pr: "KREH-seh RAH-pee-doh oh LEHN-toh" },
  { cat: "garden", topic: "size", es: "¿Hay que podarla?", en: "Does it need pruning?", pr: "eye keh poh-DAR-lah" },
  { cat: "garden", topic: "size", es: "¿Las raíces son agresivas?", en: "Are the roots invasive?", pr: "lahs rah-EE-sehs sohn ah-greh-SEE-vahs", note: "Ask before planting a tree near a wall, pool or pipes." },
  { cat: "garden", topic: "size", es: "¿Dura todo el año?", en: "Does it last all year? (perennial)", pr: "DOO-rah TOH-doh ehl AH-nyoh" },
  { cat: "garden", topic: "size", kind: "hear", es: "Es de temporada", en: "It's seasonal (won't last)", pr: "ehs deh tehm-poh-RAH-dah" },
  { cat: "garden", topic: "size", kind: "hear", es: "Llega a medir dos metros", en: "It gets up to two meters", pr: "YEH-gah ah meh-DEER dohs MEH-trohs", note: "1 metro ≈ 3.3 feet." },

  // Climate & location
  { cat: "garden", topic: "climate", es: "¿Se da bien aquí?", en: "Does it do well here?", pr: "seh dah bee-EHN ah-KEE", note: "The single most useful question: the staff know what survives locally." },
  { cat: "garden", topic: "climate", es: "¿Aguanta el calor?", en: "Can it take the heat?", pr: "ah-GWAHN-tah ehl kah-LOR" },
  { cat: "garden", topic: "climate", es: "¿Aguanta la brisa del mar?", en: "Can it handle the sea breeze and salt?", pr: "ah-GWAHN-tah lah BREE-sah dehl mar", note: "Near the beach, ask this first. Salt spray burns many plants." },
  { cat: "garden", topic: "climate", es: "¿Aguanta el viento?", en: "Can it take wind?", pr: "ah-GWAHN-tah ehl vee-EHN-toh" },
  { cat: "garden", topic: "climate", es: "¿Es una planta de la región?", en: "Is it native to the area?", pr: "ehs OO-nah PLAHN-tah deh lah reh-hee-OHN" },
  { cat: "garden", topic: "climate", es: "Es para una terraza cerca del mar", en: "It's for a terrace near the sea", pr: "ehs PAH-rah OO-nah teh-RRAH-sah SEHR-kah dehl mar" },

  // Pests & problems
  { cat: "garden", topic: "pests", es: "Mi planta tiene las hojas amarillas", en: "My plant has yellow leaves", pr: "mee PLAHN-tah tee-EH-neh lahs OH-hahs ah-mah-REE-yahs" },
  { cat: "garden", topic: "pests", es: "Las hojas se están secando", en: "The leaves are drying out", pr: "lahs OH-hahs seh ehs-TAHN seh-KAHN-doh" },
  { cat: "garden", topic: "pests", es: "Tiene bichitos", en: "It has little bugs", pr: "tee-EH-neh bee-CHEE-tohs", note: "Show them a photo on your phone. It beats describing it." },
  { cat: "garden", topic: "pests", es: "¿Qué le puedo poner?", en: "What can I put on it?", pr: "keh leh PWEH-doh poh-NEHR" },
  { cat: "garden", topic: "pests", es: "¿Tiene algo orgánico?", en: "Do you have something organic?", pr: "tee-EH-neh AHL-goh or-GAH-nee-koh" },
  { cat: "garden", topic: "pests", es: "¿Tiene algo para las hormigas?", en: "Do you have something for ants?", pr: "tee-EH-neh AHL-goh PAH-rah lahs or-MEE-gahs", note: "Leafcutter ants (hormiga arriera) can strip a plant overnight." },
  { cat: "garden", topic: "pests", kind: "word", es: "la plaga", en: "pest / infestation", pr: "lah PLAH-gah" },
  { cat: "garden", topic: "pests", kind: "word", es: "el hongo", en: "fungus", pr: "ehl OHN-goh" },
  { cat: "garden", topic: "pests", kind: "word", es: "la cochinilla", en: "mealybug / scale", pr: "lah koh-chee-NEE-yah" },
  { cat: "garden", topic: "pests", kind: "word", es: "la mosca blanca", en: "whitefly", pr: "lah MOHS-kah BLAHN-kah" },
  { cat: "garden", topic: "pests", kind: "word", es: "el pulgón", en: "aphid", pr: "ehl pool-GOHN" },
  { cat: "garden", topic: "pests", kind: "word", es: "aceite de neem", en: "neem oil", pr: "ah-SAY-teh deh neem" },

  // Pets & kids
  { cat: "garden", topic: "safety", es: "¿Es tóxica para perros o gatos?", en: "Is it toxic to dogs or cats?", pr: "ehs TOHK-see-kah PAH-rah PEH-rrohs oh GAH-tohs" },
  { cat: "garden", topic: "safety", es: "¿Es segura para niños?", en: "Is it safe for kids?", pr: "ehs seh-GOO-rah PAH-rah NEE-nyohs" },
  { cat: "garden", topic: "safety", es: "¿Tiene espinas?", en: "Does it have thorns / spines?", pr: "tee-EH-neh ehs-PEE-nahs" },
  { cat: "garden", topic: "safety", es: "¿La savia irrita la piel?", en: "Does the sap irritate skin?", pr: "lah SAH-vee-ah ee-RREE-tah lah pee-EHL" },

  // Flowers & fruit
  { cat: "garden", topic: "bloom", es: "¿Cuándo florea?", en: "When does it flower?", pr: "KWAHN-doh floh-REH-ah", note: "“Florece” is also correct; “florea” is what you'll usually hear in Mexico." },
  { cat: "garden", topic: "bloom", es: "¿De qué color es la flor?", en: "What color is the flower?", pr: "deh keh koh-LOR ehs lah flor" },
  { cat: "garden", topic: "bloom", es: "¿Da fruto? ¿En cuánto tiempo?", en: "Does it bear fruit? How long until it does?", pr: "dah FROO-toh? ehn KWAHN-toh tee-EHM-poh" },
  { cat: "garden", topic: "bloom", es: "¿Necesita otra para dar fruto?", en: "Does it need a second plant to fruit?", pr: "neh-seh-SEE-tah OH-trah PAH-rah dar FROO-toh" },
  { cat: "garden", topic: "bloom", es: "¿Atrae colibríes o mariposas?", en: "Does it attract hummingbirds or butterflies?", pr: "ah-TRAH-eh koh-lee-BREE-ehs oh mah-ree-POH-sahs" },
  { cat: "garden", topic: "bloom", es: "¿Huele?", en: "Is it fragrant? (lit. does it smell?)", pr: "WEH-leh" },

  // Finding plants
  { cat: "garden", topic: "find", es: "Busco una planta para…", en: "I'm looking for a plant for…", pr: "BOOS-koh OO-nah PLAHN-tah PAH-rah" },
  { cat: "garden", topic: "find", es: "¿Cómo se llama esta planta?", en: "What's this plant called?", pr: "KOH-moh seh YAH-mah EHS-tah PLAHN-tah" },
  { cat: "garden", topic: "find", es: "Quiero algo que no necesite mucho cuidado", en: "I want something low-maintenance", pr: "kee-EH-roh AHL-goh keh noh neh-seh-SEE-teh MOO-choh kwee-DAH-doh" },
  { cat: "garden", topic: "find", es: "¿Tienen plantas de sombra?", en: "Do you have shade plants?", pr: "tee-EH-nehn PLAHN-tahs deh SOHM-brah" },
  { cat: "garden", topic: "find", es: "¿Tienen árboles frutales?", en: "Do you have fruit trees?", pr: "tee-EH-nehn AR-boh-lehs froo-TAH-lehs" },
  { cat: "garden", topic: "find", es: "¿Tienen semillas de…?", en: "Do you have seeds for…?", pr: "tee-EH-nehn seh-MEE-yahs deh" },
  { cat: "garden", topic: "find", es: "¿Tienen más grandes / más chicas?", en: "Do you have bigger / smaller ones?", pr: "tee-EH-nehn mahs GRAHN-dehs / mahs CHEE-kahs" },
  { cat: "garden", topic: "find", es: "¿Me la puede apartar?", en: "Can you set it aside for me?", pr: "meh lah PWEH-deh ah-par-TAR" },

  // Buying & delivery
  { cat: "garden", topic: "buy", es: "¿Cuánto cuesta esta?", en: "How much is this one?", pr: "KWAHN-toh KWEHS-tah EHS-tah" },
  { cat: "garden", topic: "buy", es: "¿Me hace descuento si llevo varias?", en: "Any discount if I take several?", pr: "meh AH-seh dehs-KWEHN-toh see YEH-voh VAH-ree-ahs" },
  { cat: "garden", topic: "buy", es: "¿Hacen entregas a domicilio?", en: "Do you deliver?", pr: "AH-sehn ehn-TREH-gahs ah doh-mee-SEE-lee-oh" },
  { cat: "garden", topic: "buy", es: "¿Cuánto cobran por llevarlo a…?", en: "How much to deliver it to…?", pr: "KWAHN-toh KOH-brahn por yeh-VAR-loh ah" },
  { cat: "garden", topic: "buy", es: "¿Me ayuda a subirla al carro?", en: "Can you help me load it into the car?", pr: "meh ah-YOO-dah ah soo-BEER-lah ahl KAH-rroh" },
  { cat: "garden", topic: "buy", es: "¿Aceptan tarjeta o solo efectivo?", en: "Do you take cards or cash only?", pr: "ah-SEHP-tahn tar-HEH-tah oh SOH-loh eh-fehk-TEE-voh" },
  { cat: "garden", topic: "buy", es: "¿Tienen garantía si se muere?", en: "Is there a guarantee if it dies?", pr: "tee-EH-nehn gah-rahn-TEE-ah see seh MWEH-reh", note: "Most don't, but it's fair to ask on trees and big plants." },

  // Tools & supplies
  { cat: "garden", topic: "tools", es: "¿Dónde están las herramientas?", en: "Where are the tools?", pr: "DOHN-deh ehs-TAHN lahs eh-rrah-mee-EHN-tahs" },
  { cat: "garden", topic: "tools", kind: "word", es: "la manguera", en: "hose", pr: "lah mahn-GEH-rah" },
  { cat: "garden", topic: "tools", kind: "word", es: "la regadera", en: "watering can", pr: "lah reh-gah-DEH-rah" },
  { cat: "garden", topic: "tools", kind: "word", es: "el aspersor", en: "sprinkler", pr: "ehl ahs-pehr-SOR" },
  { cat: "garden", topic: "tools", kind: "word", es: "riego por goteo", en: "drip irrigation", pr: "ree-EH-goh por goh-TEH-oh" },
  { cat: "garden", topic: "tools", kind: "word", es: "las tijeras de podar", en: "pruning shears", pr: "lahs tee-HEH-rahs deh poh-DAR" },
  { cat: "garden", topic: "tools", kind: "word", es: "la pala", en: "shovel", pr: "lah PAH-lah" },
  { cat: "garden", topic: "tools", kind: "word", es: "la palita", en: "hand trowel", pr: "lah pah-LEE-tah" },
  { cat: "garden", topic: "tools", kind: "word", es: "el rastrillo", en: "rake", pr: "ehl rahs-TREE-yoh" },
  { cat: "garden", topic: "tools", kind: "word", es: "los guantes", en: "gloves", pr: "lohs GWAHN-tehs" },
  { cat: "garden", topic: "tools", kind: "word", es: "la malla sombra", en: "shade cloth", pr: "lah MAH-yah SOHM-brah" },

  // Kinds of plants
  { cat: "garden", topic: "kinds", kind: "word", es: "la palma", en: "palm", pr: "lah PAHL-mah" },
  { cat: "garden", topic: "kinds", kind: "word", es: "la suculenta", en: "succulent", pr: "lah soo-koo-LEHN-tah" },
  { cat: "garden", topic: "kinds", kind: "word", es: "el cactus", en: "cactus", pr: "ehl KAHK-toos" },
  { cat: "garden", topic: "kinds", kind: "word", es: "el helecho", en: "fern", pr: "ehl eh-LEH-choh" },
  { cat: "garden", topic: "kinds", kind: "word", es: "la enredadera", en: "climbing vine", pr: "lah ehn-reh-dah-DEH-rah" },
  { cat: "garden", topic: "kinds", kind: "word", es: "la bugambilia", en: "bougainvillea", pr: "lah boo-gahm-BEE-lee-ah" },
  { cat: "garden", topic: "kinds", kind: "word", es: "el arbusto", en: "shrub", pr: "ehl ar-BOOS-toh" },
  { cat: "garden", topic: "kinds", kind: "word", es: "el seto", en: "hedge", pr: "ehl SEH-toh" },
  { cat: "garden", topic: "kinds", kind: "word", es: "el árbol frutal", en: "fruit tree", pr: "ehl AR-bohl froo-TAHL" },
  { cat: "garden", topic: "kinds", kind: "word", es: "el pasto", en: "lawn grass", pr: "ehl PAHS-toh" },
  { cat: "garden", topic: "kinds", kind: "word", es: "el cubresuelo", en: "ground cover", pr: "ehl koo-breh-SWEH-loh" },
  { cat: "garden", topic: "kinds", kind: "word", es: "hierbas de olor", en: "cooking herbs", pr: "YEHR-bahs deh oh-LOR" },
  { cat: "garden", topic: "kinds", kind: "word", es: "la albahaca", en: "basil", pr: "lah ahl-bah-AH-kah" },
  { cat: "garden", topic: "kinds", kind: "word", es: "la planta de ornato", en: "ornamental plant", pr: "lah PLAHN-tah deh or-NAH-toh" },

  // ---------- Gas station ----------
  // Filling up
  { cat: "gas", topic: "fill", es: "Lleno, por favor.", en: "Fill it up, please.", pr: "YEH-noh, por fah-VOR", note: "In Mexico an attendant pumps the gas for you. Stay in the car and tell them what you want." },
  { cat: "gas", topic: "fill", es: "Quinientos pesos de magna, por favor.", en: "500 pesos of regular, please.", pr: "kee-nee-EHN-tohs PEH-sohs deh MAHG-nah, por fah-VOR", note: "Magna = regular (green pump). Premium = red pump. Diésel = black pump." },
  { cat: "gas", topic: "fill", es: "Doscientos de premium.", en: "200 pesos of premium.", pr: "dohs-see-EHN-tohs deh PREH-mee-oom" },
  { cat: "gas", topic: "fill", es: "¿Me puede mostrar que está en ceros?", en: "Can you show me the pump is at zero?", pr: "meh PWEH-deh mohs-TRAR keh ehs-TAH ehn SEH-rohs", note: "Look at the pump before they start. The most common trick is starting from the last customer's total." },
  { cat: "gas", topic: "fill", es: "¿Está en ceros?", en: "Is it at zero?", pr: "ehs-TAH ehn SEH-rohs" },
  { cat: "gas", topic: "fill", es: "¿Cuál es la magna?", en: "Which one is regular?", pr: "kwahl ehs lah MAHG-nah" },
  { cat: "gas", topic: "fill", es: "El tanque está de este lado.", en: "The gas cap is on this side.", pr: "ehl TAHN-keh ehs-TAH deh EHS-teh LAH-doh" },
  { cat: "gas", topic: "fill", es: "Es un coche rentado.", en: "It's a rental car.", pr: "ehs oon KOH-cheh rehn-TAH-doh" },
  { cat: "gas", topic: "fill", kind: "hear", es: "¿Cuánto le cargo?", en: "How much should I put in?", pr: "KWAHN-toh leh KAR-goh" },
  { cat: "gas", topic: "fill", kind: "hear", es: "¿Lleno?", en: "Fill it up?", pr: "YEH-noh" },
  { cat: "gas", topic: "fill", kind: "hear", es: "¿Magna o premium?", en: "Regular or premium?", pr: "MAHG-nah oh PREH-mee-oom" },
  { cat: "gas", topic: "fill", kind: "hear", es: "Está en ceros, joven.", en: "It's at zero.", pr: "ehs-TAH ehn SEH-rohs, HOH-vehn", note: "Joven, güero and jefe are friendly ways attendants address you." },
  { cat: "gas", topic: "fill", kind: "hear", es: "¿Me abre el tanque?", en: "Can you open the gas cap?", pr: "meh AH-breh ehl TAHN-keh", note: "They want you to pop the fuel door from inside." },
  { cat: "gas", topic: "fill", kind: "hear", es: "Ya quedó.", en: "All done.", pr: "yah keh-DOH" },

  // Paying & avoiding scams
  { cat: "gas", topic: "pay", es: "¿Puedo pagar con tarjeta aquí en la bomba?", en: "Can I pay by card here at the pump?", pr: "PWEH-doh pah-GAR kohn tar-HEH-tah ah-KEE ehn lah BOHM-bah" },
  { cat: "gas", topic: "pay", es: "Voy a pagar con tarjeta.", en: "I'll pay by card.", pr: "voy ah pah-GAR kohn tar-HEH-tah", note: "They bring the terminal to your window. Keep your card where you can see it." },
  { cat: "gas", topic: "pay", es: "En efectivo.", en: "Cash.", pr: "ehn eh-fehk-TEE-voh" },
  { cat: "gas", topic: "pay", es: "Aquí tiene quinientos.", en: "Here's 500.", pr: "ah-KEE tee-EH-neh kee-nee-EHN-tohs", note: "Say the amount out loud as you hand it over. It stops the bill-swap trick." },
  { cat: "gas", topic: "pay", es: "Le di un billete de quinientos.", en: "I gave you a 500 bill.", pr: "leh dee oon bee-YEH-teh deh kee-nee-EHN-tohs", note: "The classic scam is swapping your 500 for a 50 and saying you underpaid. Stand firm." },
  { cat: "gas", topic: "pay", es: "¿Me da mi cambio, por favor?", en: "May I have my change, please?", pr: "meh dah mee KAHM-bee-oh, por fah-VOR" },
  { cat: "gas", topic: "pay", es: "Me cobró de más.", en: "You charged me too much.", pr: "meh koh-BROH deh MAHS" },
  { cat: "gas", topic: "pay", es: "¿Me da un ticket?", en: "Can I have a receipt?", pr: "meh dah oon TEE-keht" },
  { cat: "gas", topic: "pay", es: "Esto es para usted.", en: "This is for you.", pr: "EHS-toh ehs PAH-rah oos-TEHD", note: "Tip the attendant 10–20 pesos, a little more if they cleaned the windshield or checked the tires." },
  { cat: "gas", topic: "pay", kind: "hear", es: "¿Efectivo o tarjeta?", en: "Cash or card?", pr: "eh-fehk-TEE-voh oh tar-HEH-tah" },
  { cat: "gas", topic: "pay", kind: "hear", es: "¿Crédito o débito?", en: "Credit or debit?", pr: "KREH-dee-toh oh DEH-bee-toh" },
  { cat: "gas", topic: "pay", kind: "hear", es: "Su NIP, por favor.", en: "Your PIN, please.", pr: "soo neep, por fah-VOR", note: "NIP is Mexican for PIN." },
  { cat: "gas", topic: "pay", kind: "hear", es: "¿Requiere factura?", en: "Do you need a tax invoice?", pr: "reh-kee-EH-reh fahk-TOO-rah", note: "A factura is an official invoice for businesses. Just say \"No, gracias.\"" },
  { cat: "gas", topic: "pay", kind: "hear", es: "Le faltan cien.", en: "You're 100 short.", pr: "leh FAHL-tahn see-EHN", note: "If you know what you handed over, say so: \"Le di quinientos.\"" },

  // Air, oil & windshield
  { cat: "gas", topic: "service", es: "¿Me revisa el aire de las llantas?", en: "Can you check the tire pressure?", pr: "meh reh-VEE-sah ehl EYE-reh deh lahs YAHN-tahs" },
  { cat: "gas", topic: "service", es: "¿Dónde hay aire?", en: "Where's the air pump?", pr: "DOHN-deh eye EYE-reh" },
  { cat: "gas", topic: "service", es: "Treinta y dos libras, por favor.", en: "32 PSI, please.", pr: "TRAYN-tah ee dohs LEE-brahs, por fah-VOR", note: "Tire pressure is given in libras (pounds)." },
  { cat: "gas", topic: "service", es: "¿Me checa el aceite?", en: "Can you check the oil?", pr: "meh CHEH-kah ehl ah-SAY-teh" },
  { cat: "gas", topic: "service", es: "¿Me limpia el parabrisas?", en: "Can you clean the windshield?", pr: "meh LEEM-pee-ah ehl pah-rah-BREE-sahs" },
  { cat: "gas", topic: "service", es: "¿Tienen agua para el radiador?", en: "Do you have water for the radiator?", pr: "tee-EH-nehn AH-gwah PAH-rah ehl rah-dee-ah-DOR" },
  { cat: "gas", topic: "service", es: "No, gracias, así está bien.", en: "No thanks, it's fine as is.", pr: "noh GRAH-see-ahs, ah-SEE ehs-TAH bee-EHN" },
  { cat: "gas", topic: "service", kind: "hear", es: "¿Le checo el aceite?", en: "Shall I check your oil?", pr: "leh CHEH-koh ehl ah-SAY-teh" },
  { cat: "gas", topic: "service", kind: "hear", es: "¿Le limpio el parabrisas?", en: "Shall I clean your windshield?", pr: "leh LEEM-pee-oh ehl pah-rah-BREE-sahs" },
  { cat: "gas", topic: "service", kind: "hear", es: "Le falta aceite.", en: "You're low on oil.", pr: "leh FAHL-tah ah-SAY-teh", note: "Sometimes true, sometimes an upsell. \"Ahorita no, gracias\" means not right now." },
  { cat: "gas", topic: "service", kind: "hear", es: "Trae baja la llanta.", en: "Your tire is low.", pr: "TRAH-eh BAH-hah lah YAHN-tah" },

  // Car trouble
  { cat: "gas", topic: "trouble", es: "Se me ponchó una llanta.", en: "I got a flat tire.", pr: "seh meh pohn-CHOH OO-nah YAHN-tah" },
  { cat: "gas", topic: "trouble", es: "¿Dónde hay una vulcanizadora?", en: "Where's a tire repair shop?", pr: "DOHN-deh eye OO-nah vool-kah-nee-sah-DOH-rah", note: "Also called a llantera. Look for tires painted on a roadside wall." },
  { cat: "gas", topic: "trouble", es: "¿Hay un mecánico cerca?", en: "Is there a mechanic nearby?", pr: "eye oon meh-KAH-nee-koh SEHR-kah" },
  { cat: "gas", topic: "trouble", es: "El coche no arranca.", en: "The car won't start.", pr: "ehl KOH-cheh noh ah-RRAHN-kah" },
  { cat: "gas", topic: "trouble", es: "Se quedó sin batería.", en: "The battery is dead.", pr: "seh keh-DOH seen bah-teh-REE-ah" },
  { cat: "gas", topic: "trouble", es: "¿Me puede pasar corriente?", en: "Can you give me a jump start?", pr: "meh PWEH-deh pah-SAR koh-rree-EHN-teh" },
  { cat: "gas", topic: "trouble", es: "Se prendió una luz en el tablero.", en: "A warning light came on.", pr: "seh prehn-dee-OH OO-nah loos ehn ehl tah-BLEH-roh" },
  { cat: "gas", topic: "trouble", es: "Se está calentando el motor.", en: "The engine is overheating.", pr: "seh ehs-TAH kah-lehn-TAHN-doh ehl moh-TOR" },
  { cat: "gas", topic: "trouble", es: "Está tirando aceite.", en: "It's leaking oil.", pr: "ehs-TAH tee-RAHN-doh ah-SAY-teh" },
  { cat: "gas", topic: "trouble", es: "¿Cuánto cuesta arreglarlo?", en: "How much to fix it?", pr: "KWAHN-toh KWEHS-tah ah-rreh-GLAR-loh" },
  { cat: "gas", topic: "trouble", es: "¿Para cuándo queda?", en: "When will it be ready?", pr: "PAH-rah KWAHN-doh KEH-dah" },
  { cat: "gas", topic: "trouble", kind: "hear", es: "Hay que cambiarla.", en: "It needs to be replaced.", pr: "eye keh kahm-bee-AR-lah" },
  { cat: "gas", topic: "trouble", kind: "hear", es: "Queda en una hora.", en: "It'll be ready in an hour.", pr: "KEH-dah ehn OO-nah OH-rah" },

  // The road ahead
  { cat: "gas", topic: "road", es: "¿Hay otra gasolinera más adelante?", en: "Is there another gas station further on?", pr: "eye OH-trah gah-soh-lee-NEH-rah mahs ah-deh-LAHN-teh" },
  { cat: "gas", topic: "road", es: "¿Qué tan lejos está la siguiente?", en: "How far is the next one?", pr: "keh tahn LEH-hohs ehs-TAH lah see-gee-EHN-teh" },
  { cat: "gas", topic: "road", es: "¿Cómo regreso a la carretera?", en: "How do I get back to the highway?", pr: "KOH-moh reh-GREH-soh ah lah kah-rreh-TEH-rah" },
  { cat: "gas", topic: "road", es: "¿Esta es la libre o la cuota?", en: "Is this the free road or the toll road?", pr: "EHS-tah ehs lah LEE-breh oh lah KWOH-tah", note: "Cuota = toll highway, faster and safer. Libre = free road through the towns." },
  { cat: "gas", topic: "road", es: "¿Cuánto cuesta la caseta?", en: "How much is the toll booth?", pr: "KWAHN-toh KWEHS-tah lah kah-SEH-tah" },
  { cat: "gas", topic: "road", es: "¿Es seguro manejar de noche por aquí?", en: "Is it safe to drive around here at night?", pr: "ehs seh-GOO-roh mah-neh-HAR deh NOH-cheh por ah-KEE" },
  { cat: "gas", topic: "road", kind: "hear", es: "Aguas con los topes.", en: "Watch out for the speed bumps.", pr: "AH-gwahs kohn lohs TOH-pehs", note: "\"¡Aguas!\" means watch out. Topes are everywhere, often unpainted." },
  { cat: "gas", topic: "road", kind: "hear", es: "Está a unos veinte kilómetros.", en: "It's about 20 kilometers away.", pr: "ehs-TAH ah OO-nohs VAYN-teh kee-LOH-meh-trohs" },
  { cat: "gas", topic: "road", kind: "hear", es: "Siga derecho hasta el retorno.", en: "Keep going straight to the U-turn.", pr: "SEE-gah deh-REH-choh AHS-tah ehl reh-TOR-noh", note: "On divided highways you often pass your turn and come back at a retorno." },

  // Restroom & snacks
  { cat: "gas", topic: "stop", es: "¿Tienen baño?", en: "Do you have a restroom?", pr: "tee-EH-nehn BAH-nyoh", note: "Gas station restrooms often cost 5–10 pesos. Carry coins." },
  { cat: "gas", topic: "stop", es: "¿Cuánto cuesta el baño?", en: "How much is the restroom?", pr: "KWAHN-toh KWEHS-tah ehl BAH-nyoh" },
  { cat: "gas", topic: "stop", es: "¿Hay papel?", en: "Is there toilet paper?", pr: "eye pah-PEHL", note: "Sometimes the attendant hands you paper when you pay." },
  { cat: "gas", topic: "stop", es: "¿Venden hielo?", en: "Do you sell ice?", pr: "VEHN-dehn YEH-loh" },
  { cat: "gas", topic: "stop", es: "Una botella de agua, por favor.", en: "A bottle of water, please.", pr: "OO-nah boh-TEH-yah deh AH-gwah, por fah-VOR" },
  { cat: "gas", topic: "stop", kind: "hear", es: "Son cinco pesos.", en: "It's five pesos.", pr: "sohn SEEN-koh PEH-sohs" },
  { cat: "gas", topic: "stop", kind: "hear", es: "El baño está cerrado.", en: "The restroom is closed.", pr: "ehl BAH-nyoh ehs-TAH seh-RRAH-doh" },

  // Car words
  { cat: "gas", topic: "car", kind: "word", es: "la gasolinera", en: "gas station", pr: "lah gah-soh-lee-NEH-rah" },
  { cat: "gas", topic: "car", kind: "word", es: "la bomba", en: "pump", pr: "lah BOHM-bah" },
  { cat: "gas", topic: "car", kind: "word", es: "el litro", en: "liter", pr: "ehl LEE-troh", note: "Gas is sold by the liter. A gallon is about 3.8 liters." },
  { cat: "gas", topic: "car", kind: "word", es: "el tanque", en: "gas tank", pr: "ehl TAHN-keh" },
  { cat: "gas", topic: "car", kind: "word", es: "la llanta", en: "tire", pr: "lah YAHN-tah" },
  { cat: "gas", topic: "car", kind: "word", es: "el aceite", en: "oil", pr: "ehl ah-SAY-teh" },
  { cat: "gas", topic: "car", kind: "word", es: "el cofre", en: "hood", pr: "ehl KOH-freh" },
  { cat: "gas", topic: "car", kind: "word", es: "la cajuela", en: "trunk", pr: "lah kah-HWEH-lah" },
  { cat: "gas", topic: "car", kind: "word", es: "los frenos", en: "brakes", pr: "lohs FREH-nohs" },
  { cat: "gas", topic: "car", kind: "word", es: "la batería", en: "battery", pr: "lah bah-teh-REE-ah" },
  { cat: "gas", topic: "car", kind: "word", es: "las llaves", en: "keys", pr: "lahs YAH-vehs" },
  { cat: "gas", topic: "car", kind: "word", es: "el tope", en: "speed bump", pr: "ehl TOH-peh" },
  { cat: "gas", topic: "car", kind: "word", es: "la caseta", en: "toll booth", pr: "lah kah-SEH-tah" },
  { cat: "gas", topic: "car", kind: "word", es: "la desviación", en: "detour", pr: "lah dehs-vee-ah-see-OHN" },

  // ---------- Pharmacy ----------
  // Saying what's wrong
  { cat: "pharmacy", topic: "symptoms", es: "Me duele la cabeza.", en: "I have a headache.", pr: "meh DWEH-leh lah kah-BEH-sah", note: "Me duele + the body part = it hurts. Me duele el estómago, me duele la garganta, me duele la espalda." },
  { cat: "pharmacy", topic: "symptoms", es: "Me duele el estómago.", en: "My stomach hurts.", pr: "meh DWEH-leh ehl ehs-TOH-mah-goh" },
  { cat: "pharmacy", topic: "symptoms", es: "Me duele la garganta.", en: "I have a sore throat.", pr: "meh DWEH-leh lah gar-GAHN-tah" },
  { cat: "pharmacy", topic: "symptoms", es: "Tengo fiebre.", en: "I have a fever.", pr: "TEHN-goh fee-EH-breh" },
  { cat: "pharmacy", topic: "symptoms", es: "Tengo tos.", en: "I have a cough.", pr: "TEHN-goh tohs", note: "Dry cough = tos seca. Cough with phlegm = tos con flemas." },
  { cat: "pharmacy", topic: "symptoms", es: "Tengo gripa.", en: "I have a cold / the flu.", pr: "TEHN-goh GREE-pah", note: "Mexicans say gripa, not gripe. It covers anything from a cold to the flu." },
  { cat: "pharmacy", topic: "symptoms", es: "Tengo la nariz tapada.", en: "My nose is stuffed up.", pr: "TEHN-goh lah nah-REES tah-PAH-dah" },
  { cat: "pharmacy", topic: "symptoms", es: "Tengo diarrea.", en: "I have diarrhea.", pr: "TEHN-goh dee-ah-RREH-ah" },
  { cat: "pharmacy", topic: "symptoms", es: "Tengo ganas de vomitar.", en: "I feel like throwing up.", pr: "TEHN-goh GAH-nahs deh voh-mee-TAR", note: "Tengo náuseas (NOW-seh-ahs) also works." },
  { cat: "pharmacy", topic: "symptoms", es: "Estoy mareado / mareada.", en: "I'm dizzy. (man / woman)", pr: "ehs-TOY mah-reh-AH-doh / mah-reh-AH-dah" },
  { cat: "pharmacy", topic: "symptoms", es: "Tengo comezón.", en: "I'm itchy.", pr: "TEHN-goh koh-meh-SOHN", note: "Comezón is the everyday Mexican word for itching." },
  { cat: "pharmacy", topic: "symptoms", es: "Me torcí el tobillo.", en: "I twisted my ankle.", pr: "meh tor-SEE ehl toh-BEE-yoh" },
  { cat: "pharmacy", topic: "symptoms", es: "No puedo dormir.", en: "I can't sleep.", pr: "noh PWEH-doh dor-MEER" },
  { cat: "pharmacy", topic: "symptoms", es: "Desde hace tres días.", en: "For three days now.", pr: "DEHS-deh AH-seh trehs DEE-ahs", note: "The answer to ¿Desde cuándo? (Since when?). Desde ayer = since yesterday." },
  { cat: "pharmacy", topic: "symptoms", kind: "hear", es: "¿Qué síntomas tiene?", en: "What symptoms do you have?", pr: "keh SEEN-toh-mahs tee-EH-neh" },
  { cat: "pharmacy", topic: "symptoms", kind: "hear", es: "¿Desde cuándo?", en: "Since when?", pr: "DEHS-deh KWAHN-doh" },
  { cat: "pharmacy", topic: "symptoms", kind: "hear", es: "¿Tiene fiebre?", en: "Do you have a fever?", pr: "tee-EH-neh fee-EH-breh" },

  // Asking for medicine
  { cat: "pharmacy", topic: "ask", es: "¿Tiene algo para el dolor de cabeza?", en: "Do you have something for a headache?", pr: "tee-EH-neh AHL-goh PAH-rah ehl doh-LOR deh kah-BEH-sah" },
  { cat: "pharmacy", topic: "ask", es: "¿Tiene algo para la gripa?", en: "Do you have something for a cold?", pr: "tee-EH-neh AHL-goh PAH-rah lah GREE-pah" },
  { cat: "pharmacy", topic: "ask", es: "¿Tiene ibuprofeno?", en: "Do you have ibuprofen?", pr: "tee-EH-neh ee-boo-proh-FEH-noh" },
  { cat: "pharmacy", topic: "ask", es: "¿Tiene paracetamol?", en: "Do you have acetaminophen (Tylenol)?", pr: "tee-EH-neh pah-rah-seh-tah-MOHL", note: "Acetaminophen is called paracetamol in Mexico." },
  { cat: "pharmacy", topic: "ask", es: "¿Tiene el genérico?", en: "Do you have the generic?", pr: "tee-EH-neh ehl heh-NEH-ree-koh", note: "Generics are much cheaper. Farmacias Similares sells mostly generics. The brand name is el de patente." },
  { cat: "pharmacy", topic: "ask", es: "¿Cuál me recomienda?", en: "Which one do you recommend?", pr: "kwahl meh reh-koh-mee-EHN-dah" },
  { cat: "pharmacy", topic: "ask", es: "¿Lo tiene en jarabe?", en: "Do you have it as a syrup?", pr: "loh tee-EH-neh ehn hah-RAH-beh", note: "en pastillas = in pills, en pomada = as an ointment, en gotas = as drops." },
  { cat: "pharmacy", topic: "ask", es: "¿Tiene algo para niños?", en: "Do you have something for children?", pr: "tee-EH-neh AHL-goh PAH-rah NEE-nyohs" },
  { cat: "pharmacy", topic: "ask", es: "¿Tienen este medicamento?", en: "Do you have this medicine?", pr: "tee-EH-nehn EHS-teh meh-dee-kah-MEHN-toh", note: "Show the box or a photo. Point to the active ingredient (sustancia activa). Brand names differ, the ingredient doesn't." },
  { cat: "pharmacy", topic: "ask", kind: "hear", es: "¿Es para usted?", en: "Is it for you?", pr: "ehs PAH-rah oos-TEHD" },
  { cat: "pharmacy", topic: "ask", kind: "hear", es: "¿Es alérgico a algún medicamento?", en: "Are you allergic to any medicine?", pr: "ehs ah-LEHR-hee-koh ah ahl-GOON meh-dee-kah-MEHN-toh" },
  { cat: "pharmacy", topic: "ask", kind: "hear", es: "No lo manejamos.", en: "We don't carry it.", pr: "noh loh mah-neh-HAH-mohs" },
  { cat: "pharmacy", topic: "ask", kind: "hear", es: "Le doy el genérico, sale más barato.", en: "I'll give you the generic, it's cheaper.", pr: "leh doy ehl heh-NEH-ree-koh, SAH-leh mahs bah-RAH-toh" },
  { cat: "pharmacy", topic: "ask", kind: "hear", es: "¿Caja chica o caja grande?", en: "Small box or big box?", pr: "KAH-hah CHEE-kah oh KAH-hah GRAHN-deh" },

  // How to take it
  { cat: "pharmacy", topic: "dose", es: "¿Cada cuánto lo tomo?", en: "How often do I take it?", pr: "KAH-dah KWAHN-toh loh TOH-moh" },
  { cat: "pharmacy", topic: "dose", es: "¿Cuántas pastillas al día?", en: "How many pills a day?", pr: "KWAHN-tahs pahs-TEE-yahs ahl DEE-ah" },
  { cat: "pharmacy", topic: "dose", es: "¿Antes o después de comer?", en: "Before or after eating?", pr: "AHN-tehs oh dehs-PWEHS deh koh-MEHR" },
  { cat: "pharmacy", topic: "dose", es: "¿Por cuántos días?", en: "For how many days?", pr: "por KWAHN-tohs DEE-ahs" },
  { cat: "pharmacy", topic: "dose", es: "¿Da sueño?", en: "Does it make you drowsy?", pr: "dah SWEH-nyoh" },
  { cat: "pharmacy", topic: "dose", es: "¿Lo puedo tomar con alcohol?", en: "Can I take it with alcohol?", pr: "loh PWEH-doh toh-MAR kohn ahl-KOHL" },
  { cat: "pharmacy", topic: "dose", es: "¿Me lo puede escribir?", en: "Can you write it down for me?", pr: "meh loh PWEH-deh ehs-kree-BEER", note: "Worth asking every time. Many pharmacists write the dose right on the box." },
  { cat: "pharmacy", topic: "dose", kind: "hear", es: "Una tableta cada ocho horas.", en: "One tablet every eight hours.", pr: "OO-nah tah-BLEH-tah KAH-dah OH-choh OH-rahs" },
  { cat: "pharmacy", topic: "dose", kind: "hear", es: "Tómelo con alimentos.", en: "Take it with food.", pr: "TOH-meh-loh kohn ah-lee-MEHN-tohs" },
  { cat: "pharmacy", topic: "dose", kind: "hear", es: "En ayunas.", en: "On an empty stomach.", pr: "ehn ah-YOO-nahs" },
  { cat: "pharmacy", topic: "dose", kind: "hear", es: "Una cucharadita cada seis horas.", en: "One teaspoon every six hours.", pr: "OO-nah koo-chah-rah-DEE-tah KAH-dah says OH-rahs" },
  { cat: "pharmacy", topic: "dose", kind: "hear", es: "Termine todo el tratamiento.", en: "Finish the whole course.", pr: "tehr-MEE-neh TOH-doh ehl trah-tah-mee-EHN-toh" },
  { cat: "pharmacy", topic: "dose", kind: "hear", es: "No lo combine con alcohol.", en: "Don't mix it with alcohol.", pr: "noh loh kohm-BEE-neh kohn ahl-KOHL" },

  // Prescriptions & the doctor
  { cat: "pharmacy", topic: "rx", es: "¿Necesito receta para esto?", en: "Do I need a prescription for this?", pr: "neh-seh-SEE-toh reh-SEH-tah PAH-rah EHS-toh", note: "Many medicines are sold without one, but antibiotics always need a Mexican prescription." },
  { cat: "pharmacy", topic: "rx", es: "¿Hay un doctor aquí?", en: "Is there a doctor here?", pr: "eye oon dohk-TOR ah-KEE", note: "Many chain pharmacies (Similares, del Ahorro, Guadalajara) have a small doctor's office next door. The visit is usually cheap and quick." },
  { cat: "pharmacy", topic: "rx", es: "Quisiera una consulta.", en: "I'd like to see the doctor.", pr: "kee-see-EH-rah OO-nah kohn-SOOL-tah" },
  { cat: "pharmacy", topic: "rx", es: "¿Cuánto cuesta la consulta?", en: "How much is the visit?", pr: "KWAHN-toh KWEHS-tah lah kohn-SOOL-tah" },
  { cat: "pharmacy", topic: "rx", es: "Tengo una receta de Estados Unidos.", en: "I have a prescription from the US.", pr: "TEHN-goh OO-nah reh-SEH-tah deh ehs-TAH-dohs oo-NEE-dohs", note: "A US prescription may not be accepted for antibiotics or controlled drugs. The doctor next door can write a Mexican one." },
  { cat: "pharmacy", topic: "rx", es: "Tomo este medicamento todos los días.", en: "I take this medicine every day.", pr: "TOH-moh EHS-teh meh-dee-kah-MEHN-toh TOH-dohs lohs DEE-ahs" },
  { cat: "pharmacy", topic: "rx", kind: "hear", es: "Ese es solo con receta.", en: "That one is prescription only.", pr: "EH-seh ehs SOH-loh kohn reh-SEH-tah" },
  { cat: "pharmacy", topic: "rx", kind: "hear", es: "Pase al consultorio de al lado.", en: "Go to the doctor's office next door.", pr: "PAH-seh ahl kohn-sool-TOH-ree-oh deh ahl LAH-doh" },
  { cat: "pharmacy", topic: "rx", kind: "hear", es: "Me tengo que quedar con la receta.", en: "I have to keep the prescription.", pr: "meh TEHN-goh keh keh-DAR kohn lah reh-SEH-tah", note: "Normal for antibiotics. Take a photo of it first." },

  // Sun, bites & stomach
  { cat: "pharmacy", topic: "beach", es: "Me quemé con el sol.", en: "I got sunburned.", pr: "meh keh-MEH kohn ehl sohl" },
  { cat: "pharmacy", topic: "beach", es: "¿Tiene gel de sábila?", en: "Do you have aloe vera gel?", pr: "tee-EH-neh hehl deh SAH-bee-lah", note: "Aloe is sábila in Mexico." },
  { cat: "pharmacy", topic: "beach", es: "¿Tiene bloqueador biodegradable?", en: "Do you have reef-safe sunscreen?", pr: "tee-EH-neh bloh-keh-ah-DOR bee-oh-deh-grah-DAH-bleh", note: "Sunscreen is bloqueador. Many cenotes and parks allow only biodegradable sunscreen." },
  { cat: "pharmacy", topic: "beach", es: "¿Tiene repelente de mosquitos?", en: "Do you have mosquito repellent?", pr: "tee-EH-neh reh-peh-LEHN-teh deh mohs-KEE-tohs" },
  { cat: "pharmacy", topic: "beach", es: "Me picaron los moscos.", en: "The mosquitoes bit me.", pr: "meh pee-KAH-rohn lohs MOHS-kohs", note: "A bite is a piquete in Mexico. Moscos = mosquitoes, casually." },
  { cat: "pharmacy", topic: "beach", es: "Tengo un piquete que se ve infectado.", en: "I have a bite that looks infected.", pr: "TEHN-goh oon pee-KEH-teh keh seh veh een-fehk-TAH-doh" },
  { cat: "pharmacy", topic: "beach", es: "Me picó un aguamala.", en: "A jellyfish stung me.", pr: "meh pee-KOH oon ah-gwah-MAH-lah", note: "Aguamala is the usual Mexican word. Medusa is also understood." },
  { cat: "pharmacy", topic: "beach", es: "Me corté con un coral.", en: "I cut myself on coral.", pr: "meh kor-TEH kohn oon koh-RAHL" },
  { cat: "pharmacy", topic: "beach", es: "Creo que algo me cayó mal.", en: "I think something I ate made me sick.", pr: "KREH-oh keh AHL-goh meh kah-YOH mahl" },
  { cat: "pharmacy", topic: "beach", es: "¿Tiene suero oral?", en: "Do you have oral rehydration drink?", pr: "tee-EH-neh SWEH-roh oh-RAHL", note: "Electrolit is the popular brand, sold at every pharmacy and OXXO." },
  { cat: "pharmacy", topic: "beach", es: "¿Tiene algo para el mareo?", en: "Do you have something for motion sickness?", pr: "tee-EH-neh AHL-goh PAH-rah ehl mah-REH-oh", note: "Handy before the Cozumel ferry." },
  { cat: "pharmacy", topic: "beach", es: "¿Tiene curitas?", en: "Do you have Band-Aids?", pr: "tee-EH-neh koo-REE-tahs" },

  // Emergencies
  { cat: "pharmacy", topic: "urgent", es: "Es una emergencia.", en: "It's an emergency.", pr: "ehs OO-nah eh-mehr-HEHN-see-ah", note: "The emergency number in Mexico is 911." },
  { cat: "pharmacy", topic: "urgent", es: "Necesito un doctor.", en: "I need a doctor.", pr: "neh-seh-SEE-toh oon dohk-TOR" },
  { cat: "pharmacy", topic: "urgent", es: "Llame a una ambulancia, por favor.", en: "Call an ambulance, please.", pr: "YAH-meh ah OO-nah ahm-boo-LAHN-see-ah, por fah-VOR" },
  { cat: "pharmacy", topic: "urgent", es: "¿Dónde está el hospital más cercano?", en: "Where is the nearest hospital?", pr: "DOHN-deh ehs-TAH ehl ohs-pee-TAHL mahs sehr-KAH-noh" },
  { cat: "pharmacy", topic: "urgent", es: "No puede respirar.", en: "He / she can't breathe.", pr: "noh PWEH-deh rehs-pee-RAR" },
  { cat: "pharmacy", topic: "urgent", es: "Soy alérgico a la penicilina.", en: "I'm allergic to penicillin.", pr: "soy ah-LEHR-hee-koh ah lah peh-nee-see-LEE-nah", note: "A woman says alérgica." },
  { cat: "pharmacy", topic: "urgent", es: "Tengo diabetes.", en: "I have diabetes.", pr: "TEHN-goh dee-ah-BEH-tehs" },
  { cat: "pharmacy", topic: "urgent", es: "Tengo la presión alta.", en: "I have high blood pressure.", pr: "TEHN-goh lah preh-see-OHN AHL-tah" },
  { cat: "pharmacy", topic: "urgent", es: "Estoy embarazada.", en: "I'm pregnant.", pr: "ehs-TOY ehm-bah-rah-SAH-dah" },
  { cat: "pharmacy", topic: "urgent", kind: "hear", es: "¿Tiene seguro médico?", en: "Do you have health insurance?", pr: "tee-EH-neh seh-GOO-roh MEH-dee-koh" },

  // Body & medicine words
  { cat: "pharmacy", topic: "words", kind: "word", es: "la cabeza", en: "head", pr: "lah kah-BEH-sah" },
  { cat: "pharmacy", topic: "words", kind: "word", es: "la garganta", en: "throat", pr: "lah gar-GAHN-tah" },
  { cat: "pharmacy", topic: "words", kind: "word", es: "el estómago", en: "stomach", pr: "ehl ehs-TOH-mah-goh" },
  { cat: "pharmacy", topic: "words", kind: "word", es: "la espalda", en: "back", pr: "lah ehs-PAHL-dah" },
  { cat: "pharmacy", topic: "words", kind: "word", es: "el pecho", en: "chest", pr: "ehl PEH-choh" },
  { cat: "pharmacy", topic: "words", kind: "word", es: "el oído", en: "ear (inner)", pr: "ehl oh-EE-doh" },
  { cat: "pharmacy", topic: "words", kind: "word", es: "la muela", en: "back tooth", pr: "lah MWEH-lah", note: "Toothache = dolor de muela." },
  { cat: "pharmacy", topic: "words", kind: "word", es: "la rodilla", en: "knee", pr: "lah roh-DEE-yah" },
  { cat: "pharmacy", topic: "words", kind: "word", es: "la piel", en: "skin", pr: "lah pee-EHL" },
  { cat: "pharmacy", topic: "words", kind: "word", es: "la pastilla", en: "pill", pr: "lah pahs-TEE-yah" },
  { cat: "pharmacy", topic: "words", kind: "word", es: "el jarabe", en: "syrup", pr: "ehl hah-RAH-beh" },
  { cat: "pharmacy", topic: "words", kind: "word", es: "la pomada", en: "ointment", pr: "lah poh-MAH-dah" },
  { cat: "pharmacy", topic: "words", kind: "word", es: "las gotas", en: "drops", pr: "lahs GOH-tahs" },
  { cat: "pharmacy", topic: "words", kind: "word", es: "la receta", en: "prescription", pr: "lah reh-SEH-tah" },
  { cat: "pharmacy", topic: "words", kind: "word", es: "el antibiótico", en: "antibiotic", pr: "ehl ahn-tee-bee-OH-tee-koh" },
  { cat: "pharmacy", topic: "words", kind: "word", es: "el termómetro", en: "thermometer", pr: "ehl tehr-MOH-meh-troh" },

  // ---------- House cleaning ----------
  // Days, hours & pay
  { cat: "clean", topic: "schedule", es: "¿Qué días puede venir?", en: "What days can you come?", pr: "keh DEE-ahs PWEH-deh veh-NEER", note: "Use usted with the person who cleans for you. It's the respectful norm." },
  { cat: "clean", topic: "schedule", es: "¿Puede venir los martes y los viernes?", en: "Can you come on Tuesdays and Fridays?", pr: "PWEH-deh veh-NEER lohs MAR-tehs ee lohs vee-EHR-nehs" },
  { cat: "clean", topic: "schedule", es: "¿A qué hora puede llegar?", en: "What time can you get here?", pr: "ah keh OH-rah PWEH-deh yeh-GAR" },
  { cat: "clean", topic: "schedule", es: "¿Cuánto cobra por día?", en: "How much do you charge per day?", pr: "KWAHN-toh KOH-brah por DEE-ah", note: "Paying by the day is common. Por hora = per hour." },
  { cat: "clean", topic: "schedule", es: "Le pago al terminar.", en: "I'll pay you when you finish.", pr: "leh PAH-goh ahl tehr-mee-NAR" },
  { cat: "clean", topic: "schedule", es: "Aquí está su pago de la semana.", en: "Here's your pay for the week.", pr: "ah-KEE ehs-TAH soo PAH-goh deh lah seh-MAH-nah" },
  { cat: "clean", topic: "schedule", es: "La próxima semana no venga, vamos a estar de viaje.", en: "Don't come next week, we'll be traveling.", pr: "lah PROHK-see-mah seh-MAH-nah noh VEHN-gah, VAH-mohs ah ehs-TAR deh vee-AH-heh" },
  { cat: "clean", topic: "schedule", es: "Si no puede venir, mándeme un mensaje.", en: "If you can't come, send me a message.", pr: "see noh PWEH-deh veh-NEER, MAHN-deh-meh oon mehn-SAH-heh", note: "WhatsApp is how almost everyone texts in Mexico." },
  { cat: "clean", topic: "schedule", es: "Le dejo la llave con el vecino.", en: "I'll leave the key with the neighbor.", pr: "leh DEH-hoh lah YAH-veh kohn ehl veh-SEE-noh" },
  { cat: "clean", topic: "schedule", kind: "hear", es: "Mañana no puedo venir.", en: "I can't come tomorrow.", pr: "mah-NYAH-nah noh PWEH-doh veh-NEER" },
  { cat: "clean", topic: "schedule", kind: "hear", es: "Voy a llegar un poquito tarde.", en: "I'm going to be a little late.", pr: "voy ah yeh-GAR oon poh-KEE-toh TAR-deh" },
  { cat: "clean", topic: "schedule", kind: "hear", es: "Ya terminé.", en: "I'm finished.", pr: "yah tehr-mee-NEH" },
  { cat: "clean", topic: "schedule", kind: "hear", es: "¿Me puede adelantar una parte?", en: "Could you advance me part of my pay?", pr: "meh PWEH-deh ah-deh-lahn-TAR OO-nah PAR-teh" },

  // What to clean today
  { cat: "clean", topic: "tasks", es: "Hoy, por favor, limpie los baños y la cocina.", en: "Today, please clean the bathrooms and the kitchen.", pr: "oy, por fah-VOR, LEEM-pee-eh lohs BAH-nyohs ee lah koh-SEE-nah" },
  { cat: "clean", topic: "tasks", es: "¿Puede barrer y trapear toda la casa?", en: "Can you sweep and mop the whole house?", pr: "PWEH-deh bah-RREHR ee trah-peh-AR TOH-dah lah KAH-sah", note: "Trapear = to mop, the Mexican word." },
  { cat: "clean", topic: "tasks", es: "Sacuda los muebles, por favor.", en: "Please dust the furniture.", pr: "sah-KOO-dah lohs MWEH-blehs, por fah-VOR" },
  { cat: "clean", topic: "tasks", es: "Limpie los vidrios, por favor.", en: "Please clean the windows.", pr: "LEEM-pee-eh lohs VEE-dree-ohs, por fah-VOR", note: "Vidrios = the glass. Ventanas = the windows themselves." },
  { cat: "clean", topic: "tasks", es: "Empiece por la recámara.", en: "Start with the bedroom.", pr: "ehm-pee-EH-seh por lah reh-KAH-mah-rah", note: "Recámara is the Mexican word for bedroom." },
  { cat: "clean", topic: "tasks", es: "Lave la terraza con la manguera.", en: "Hose down the terrace.", pr: "LAH-veh lah teh-RRAH-sah kohn lah mahn-GEH-rah" },
  { cat: "clean", topic: "tasks", es: "Saque la basura, por favor.", en: "Please take out the trash.", pr: "SAH-keh lah bah-SOO-rah, por fah-VOR" },
  { cat: "clean", topic: "tasks", es: "Riegue las plantas, por favor.", en: "Please water the plants.", pr: "ree-EH-geh lahs PLAHN-tahs, por fah-VOR" },
  { cat: "clean", topic: "tasks", es: "Hoy no hace falta limpiar arriba.", en: "No need to clean upstairs today.", pr: "oy noh AH-seh FAHL-tah leem-pee-AR ah-RREE-bah" },
  { cat: "clean", topic: "tasks", es: "Si le da tiempo, limpie el refri.", en: "If you have time, clean the fridge.", pr: "see leh dah tee-EHM-poh, LEEM-pee-eh ehl REH-free" },
  { cat: "clean", topic: "tasks", es: "Lo más importante hoy es…", en: "The most important thing today is…", pr: "loh mahs eem-por-TAHN-teh oy ehs" },
  { cat: "clean", topic: "tasks", kind: "hear", es: "¿Qué quiere que haga hoy?", en: "What would you like me to do today?", pr: "keh kee-EH-reh keh AH-gah oy" },
  { cat: "clean", topic: "tasks", kind: "hear", es: "¿Por dónde empiezo?", en: "Where should I start?", pr: "por DOHN-deh ehm-pee-EH-soh" },

  // Laundry & beds
  { cat: "clean", topic: "laundry", es: "¿Puede lavar la ropa?", en: "Can you do the laundry?", pr: "PWEH-deh lah-VAR lah ROH-pah" },
  { cat: "clean", topic: "laundry", es: "Cambie las sábanas, por favor.", en: "Please change the sheets.", pr: "KAHM-bee-eh lahs SAH-bah-nahs, por fah-VOR" },
  { cat: "clean", topic: "laundry", es: "Tienda las camas, por favor.", en: "Please make the beds.", pr: "tee-EHN-dah lahs KAH-mahs, por fah-VOR", note: "Tender la cama = to make the bed." },
  { cat: "clean", topic: "laundry", es: "Cuelgue la ropa en el tendedero.", en: "Hang the clothes on the line.", pr: "KWEHL-geh lah ROH-pah ehn ehl tehn-deh-DEH-roh" },
  { cat: "clean", topic: "laundry", es: "La ropa blanca va aparte.", en: "The whites go separately.", pr: "lah ROH-pah BLAHN-kah vah ah-PAR-teh" },
  { cat: "clean", topic: "laundry", es: "Esto no va en la secadora.", en: "This doesn't go in the dryer.", pr: "EHS-toh noh vah ehn lah seh-kah-DOH-rah" },
  { cat: "clean", topic: "laundry", es: "Lave esto a mano, por favor.", en: "Please wash this by hand.", pr: "LAH-veh EHS-toh ah MAH-noh, por fah-VOR" },
  { cat: "clean", topic: "laundry", es: "¿Puede planchar estas camisas?", en: "Can you iron these shirts?", pr: "PWEH-deh plahn-CHAR EHS-tahs kah-MEE-sahs" },
  { cat: "clean", topic: "laundry", es: "Las toallas limpias van aquí.", en: "The clean towels go here.", pr: "lahs toh-AH-yahs LEEM-pee-ahs vahn ah-KEE" },
  { cat: "clean", topic: "laundry", kind: "hear", es: "¿Con cloro o sin cloro?", en: "With bleach or without?", pr: "kohn KLOH-roh oh seen KLOH-roh" },
  { cat: "clean", topic: "laundry", kind: "hear", es: "¿Dónde guardo las sábanas?", en: "Where do I put the sheets away?", pr: "DOHN-deh GWAR-doh lahs SAH-bah-nahs" },

  // Kitchen & dishes
  { cat: "clean", topic: "kitchen", es: "Lave los trastes, por favor.", en: "Please wash the dishes.", pr: "LAH-veh lohs TRAHS-tehs, por fah-VOR", note: "Trastes is the everyday Mexican word for dishes." },
  { cat: "clean", topic: "kitchen", es: "Limpie la estufa y el horno.", en: "Clean the stove and the oven.", pr: "LEEM-pee-eh lah ehs-TOO-fah ee ehl OR-noh" },
  { cat: "clean", topic: "kitchen", es: "Por favor, no tire esta comida.", en: "Please don't throw out this food.", pr: "por fah-VOR, noh TEE-reh EHS-tah koh-MEE-dah" },
  { cat: "clean", topic: "kitchen", es: "Tire lo que esté echado a perder.", en: "Throw out anything that's gone bad.", pr: "TEE-reh loh keh ehs-TEH eh-CHAH-doh ah pehr-DEHR" },
  { cat: "clean", topic: "kitchen", es: "Los trastes limpios van en esta alacena.", en: "The clean dishes go in this cupboard.", pr: "lohs TRAHS-tehs LEEM-pee-ohs vahn ehn EHS-tah ah-lah-SEH-nah" },
  { cat: "clean", topic: "kitchen", es: "Esto no va en el lavatrastes.", en: "This doesn't go in the dishwasher.", pr: "EHS-toh noh vah ehn ehl lah-vah-TRAHS-tehs" },
  { cat: "clean", topic: "kitchen", es: "Limpie el garrafón y la despensa.", en: "Clean the water jug and the pantry.", pr: "LEEM-pee-eh ehl gah-rrah-FOHN ee lah dehs-PEHN-sah", note: "Garrafón = the big 20-liter drinking water jug." },
  { cat: "clean", topic: "kitchen", kind: "hear", es: "¿Esto lo tiro?", en: "Should I throw this out?", pr: "EHS-toh loh TEE-roh" },
  { cat: "clean", topic: "kitchen", kind: "hear", es: "¿Esto dónde va?", en: "Where does this go?", pr: "EHS-toh DOHN-deh vah" },

  // Please be careful with…
  { cat: "clean", topic: "careful", es: "Cuidado con esto, es frágil.", en: "Careful with this, it's fragile.", pr: "kwee-DAH-doh kohn EHS-toh, ehs FRAH-heel" },
  { cat: "clean", topic: "careful", es: "No use cloro en el mármol, por favor.", en: "Please don't use bleach on the marble.", pr: "noh OO-seh KLOH-roh ehn ehl MAR-mohl, por fah-VOR" },
  { cat: "clean", topic: "careful", es: "Use esto para la madera.", en: "Use this on the wood.", pr: "OO-seh EHS-toh PAH-rah lah mah-DEH-rah" },
  { cat: "clean", topic: "careful", es: "No mueva los papeles del escritorio.", en: "Don't move the papers on the desk.", pr: "noh MWEH-vah lohs pah-PEH-lehs dehl ehs-kree-TOH-ree-oh" },
  { cat: "clean", topic: "careful", es: "Apague el aire al salir.", en: "Turn off the AC when you leave.", pr: "ah-PAH-geh ehl AY-reh ahl sah-LEER", note: "El aire = the air conditioning." },
  { cat: "clean", topic: "careful", es: "Cierre bien la puerta al salir.", en: "Lock up well when you leave.", pr: "see-EH-rreh bee-EHN lah PWEHR-tah ahl sah-LEER" },
  { cat: "clean", topic: "careful", es: "No deje salir al perro.", en: "Don't let the dog out.", pr: "noh DEH-heh sah-LEER ahl PEH-rroh" },
  { cat: "clean", topic: "careful", es: "Dele de comer al gato, por favor.", en: "Please feed the cat.", pr: "DEH-leh deh koh-MEHR ahl GAH-toh, por fah-VOR" },
  { cat: "clean", topic: "careful", es: "Si se rompe algo, no se preocupe, nada más avíseme.", en: "If something breaks, don't worry, just let me know.", pr: "see seh ROHM-peh AHL-goh, noh seh preh-oh-KOO-peh, NAH-dah mahs ah-VEE-seh-meh" },

  // Supplies
  { cat: "clean", topic: "supplies", es: "¿Qué productos necesita?", en: "What supplies do you need?", pr: "keh proh-DOOK-tohs neh-seh-SEE-tah" },
  { cat: "clean", topic: "supplies", es: "Hágame una lista de lo que falta.", en: "Make me a list of what we're out of.", pr: "AH-gah-meh OO-nah LEES-tah deh loh keh FAHL-tah" },
  { cat: "clean", topic: "supplies", es: "Los productos de limpieza están aquí.", en: "The cleaning supplies are here.", pr: "lohs proh-DOOK-tohs deh leem-pee-EH-sah ehs-TAHN ah-KEE" },
  { cat: "clean", topic: "supplies", kind: "hear", es: "Ya se acabó el cloro.", en: "The bleach is all gone.", pr: "yah seh ah-kah-BOH ehl KLOH-roh" },
  { cat: "clean", topic: "supplies", kind: "hear", es: "Hace falta jabón para la ropa.", en: "We need laundry soap.", pr: "AH-seh FAHL-tah hah-BOHN PAH-rah lah ROH-pah" },
  { cat: "clean", topic: "supplies", kind: "hear", es: "Necesito una jerga nueva.", en: "I need a new floor cloth.", pr: "neh-seh-SEE-toh OO-nah HEHR-gah NWEH-vah" },
  { cat: "clean", topic: "supplies", kind: "word", es: "la escoba", en: "broom", pr: "lah ehs-KOH-bah" },
  { cat: "clean", topic: "supplies", kind: "word", es: "el recogedor", en: "dustpan", pr: "ehl reh-koh-heh-DOR" },
  { cat: "clean", topic: "supplies", kind: "word", es: "el trapeador", en: "mop", pr: "ehl trah-peh-ah-DOR" },
  { cat: "clean", topic: "supplies", kind: "word", es: "la jerga", en: "floor cloth", pr: "lah HEHR-gah", note: "The thick cloth wrapped on a squeegee or mop to wash tile floors." },
  { cat: "clean", topic: "supplies", kind: "word", es: "la cubeta", en: "bucket", pr: "lah koo-BEH-tah" },
  { cat: "clean", topic: "supplies", kind: "word", es: "el cloro", en: "bleach", pr: "ehl KLOH-roh" },
  { cat: "clean", topic: "supplies", kind: "word", es: "el jabón en polvo", en: "laundry powder", pr: "ehl hah-BOHN ehn POHL-voh" },
  { cat: "clean", topic: "supplies", kind: "word", es: "el suavizante", en: "fabric softener", pr: "ehl swah-vee-SAHN-teh" },
  { cat: "clean", topic: "supplies", kind: "word", es: "la fibra", en: "scrub sponge", pr: "lah FEE-brah" },
  { cat: "clean", topic: "supplies", kind: "word", es: "la franela", en: "dust cloth", pr: "lah frah-NEH-lah" },
  { cat: "clean", topic: "supplies", kind: "word", es: "las bolsas de basura", en: "trash bags", pr: "lahs BOHL-sahs deh bah-SOO-rah" },
  { cat: "clean", topic: "supplies", kind: "word", es: "los guantes de hule", en: "rubber gloves", pr: "lohs GWAHN-tehs deh OO-leh" },
  { cat: "clean", topic: "supplies", kind: "word", es: "la aspiradora", en: "vacuum cleaner", pr: "lah ahs-pee-rah-DOH-rah" },
  { cat: "clean", topic: "supplies", kind: "word", es: "el limpiador multiusos", en: "all-purpose cleaner", pr: "ehl leem-pee-ah-DOR mool-tee-OO-sohs", note: "Many people just say el Fabuloso, after the popular brand." },

  // Thanks & small talk
  { cat: "clean", topic: "chat", es: "Muchas gracias, quedó muy bonito.", en: "Thank you, it looks great.", pr: "MOO-chahs GRAH-see-ahs, keh-DOH mooy boh-NEE-toh" },
  { cat: "clean", topic: "chat", es: "¿Gusta un café o un vaso de agua?", en: "Would you like a coffee or a glass of water?", pr: "GOOS-tah oon kah-FEH oh oon VAH-soh deh AH-gwah", note: "¿Gusta…? is a warm, polite Mexican way to offer something." },
  { cat: "clean", topic: "chat", es: "Si tiene hambre, agarre algo del refri.", en: "If you're hungry, help yourself to something from the fridge.", pr: "see tee-EH-neh AHM-breh, ah-GAH-rreh AHL-goh dehl REH-free" },
  { cat: "clean", topic: "chat", es: "¿Cómo está su familia?", en: "How is your family?", pr: "KOH-moh ehs-TAH soo fah-MEE-lee-ah" },
  { cat: "clean", topic: "chat", es: "Tómese el día, se lo pago igual.", en: "Take the day off, I'll pay you anyway.", pr: "TOH-meh-seh ehl DEE-ah, seh loh PAH-goh ee-GWAHL" },
  { cat: "clean", topic: "chat", es: "Aquí está su aguinaldo.", en: "Here's your Christmas bonus.", pr: "ah-KEE ehs-TAH soo ah-gee-NAHL-doh", note: "By Mexican law, household workers get an aguinaldo of at least 15 days' pay by December 20." },
  { cat: "clean", topic: "chat", es: "¿Conoce a alguien que haga jardinería?", en: "Do you know anyone who does gardening?", pr: "koh-NOH-seh ah AHL-gee-ehn keh AH-gah har-dee-neh-REE-ah" },
  { cat: "clean", topic: "chat", kind: "hear", es: "Con permiso, ya me voy.", en: "Excuse me, I'm heading out now.", pr: "kohn pehr-MEE-soh, yah meh voy" },
  { cat: "clean", topic: "chat", kind: "hear", es: "Que le vaya bien.", en: "Have a good one. (lit. may it go well for you)", pr: "keh leh VAH-yah bee-EHN" },
];
