// es = Spanish, en = English, pr = pronunciation for English speakers (CAPS = stressed syllable), note = optional tip
// kind: omitted = something you say, "hear" = something they'll say to you, "word" = a single vocabulary word
const CATEGORIES = [
  { id: "daily", name: "Everyday", es: "Diario", icon: "👋", topics: [
    { id: "greet", name: "Hellos & goodbyes", es: "Saludos", icon: "👋" },
    { id: "polite", name: "Please, thanks, sorry", es: "Cortesía", icon: "🙏" },
    { id: "understand", name: "Understanding each other", es: "No entiendo", icon: "🤔" },
    { id: "directions", name: "Directions", es: "Direcciones", icon: "🧭" },
    { id: "help", name: "Help & odds and ends", es: "Ayuda", icon: "🙋" },
    { id: "casual", name: "Casual Mexican", es: "Coloquial", icon: "😎" },
  ] },
  { id: "food", name: "Restaurant", short: "Food", es: "Restaurante", icon: "🌮", topics: [
    { id: "seat", name: "Getting a table", es: "La mesa", icon: "🪑" },
    { id: "order", name: "Ordering", es: "Pedir", icon: "📝" },
    { id: "custom", name: "Spicy, allergies & diet", es: "Picante y alergias", icon: "🌶️" },
    { id: "drinks", name: "Drinks", es: "Bebidas", icon: "🍺" },
    { id: "meal", name: "During the meal", es: "Durante la comida", icon: "🍽️" },
    { id: "pay", name: "Paying the check", es: "La cuenta", icon: "💳" },
  ] },
  { id: "store", name: "Store", es: "Tienda", icon: "🛍️", topics: [
    { id: "find", name: "Finding things", es: "Buscar", icon: "🔍" },
    { id: "price", name: "Prices & haggling", es: "Precios", icon: "🏷️" },
    { id: "sizes", name: "Sizes & colors", es: "Tallas", icon: "👕" },
    { id: "pay", name: "Paying & change", es: "Pagar", icon: "💵" },
    { id: "register", name: "At the register", es: "En la caja", icon: "🧾" },
    { id: "errands", name: "Market, pharmacy & errands", es: "Mandados", icon: "🧺" },
  ] },
  { id: "garden", name: "Garden", es: "Vivero", icon: "🌱", topics: [
    { id: "water", name: "Water requirements", es: "Riego", icon: "💧" },
    { id: "light", name: "Light requirements", es: "Luz y sol", icon: "☀️" },
    { id: "soil", name: "Soil & fertilizer", es: "Tierra y abono", icon: "🟫" },
    { id: "pots", name: "Pots & planting", es: "Macetas", icon: "🪴" },
    { id: "size", name: "Size & growth", es: "Tamaño", icon: "📏" },
    { id: "climate", name: "Heat, wind & sea air", es: "Clima", icon: "🌊" },
    { id: "pests", name: "Pests & problems", es: "Plagas", icon: "🐛" },
    { id: "safety", name: "Pets & kids", es: "Mascotas y niños", icon: "🐶" },
    { id: "bloom", name: "Flowers & fruit", es: "Flores y frutos", icon: "🌺" },
    { id: "find", name: "Finding a plant", es: "Buscar plantas", icon: "🔍" },
    { id: "buy", name: "Buying & delivery", es: "Compra y entrega", icon: "🚚" },
    { id: "tools", name: "Tools & supplies", es: "Herramientas", icon: "🧤" },
    { id: "kinds", name: "Kinds of plants", es: "Tipos de plantas", icon: "🌴" },
  ] },
  { id: "gas", name: "Gas station", short: "Gas", es: "Gasolinera", icon: "⛽", topics: [
    { id: "fill", name: "Filling up", es: "Cargar gasolina", icon: "⛽" },
    { id: "pay", name: "Paying & avoiding scams", es: "Pagar sin trampas", icon: "💵" },
    { id: "service", name: "Air, oil & windshield", es: "Aire y aceite", icon: "🛞" },
    { id: "trouble", name: "Car trouble", es: "Problemas con el coche", icon: "🔧" },
    { id: "road", name: "The road ahead", es: "La carretera", icon: "🛣️" },
    { id: "stop", name: "Restroom & snacks", es: "Baño y tienda", icon: "🚻" },
    { id: "car", name: "Car words", es: "Partes del coche", icon: "🚗" },
  ] },
];

const PHRASES = [
  // ---------- Everyday ----------
  { cat: "daily", topic: "greet", es: "Hola", en: "Hello", pr: "OH-lah" },
  { cat: "daily", topic: "greet", es: "Buenos días", en: "Good morning", pr: "BWEH-nohs DEE-ahs", note: "Use until about noon. Greeting people when you walk into a small shop or elevator is expected." },
  { cat: "daily", topic: "greet", es: "Buenas tardes", en: "Good afternoon", pr: "BWEH-nahs TAR-dehs", note: "From noon until dark." },
  { cat: "daily", topic: "greet", es: "Buenas noches", en: "Good evening / Good night", pr: "BWEH-nahs NOH-chehs", note: "Used both as a greeting after dark and as goodbye." },
  { cat: "daily", topic: "greet", es: "¿Qué tal?", en: "How's it going?", pr: "keh TAHL" },
  { cat: "daily", topic: "greet", es: "¿Cómo está?", en: "How are you? (polite)", pr: "KOH-moh ehs-TAH", note: "Formal \"usted\" form. Use it with strangers, older people and staff." },
  { cat: "daily", topic: "greet", es: "¿Cómo estás?", en: "How are you? (casual)", pr: "KOH-moh ehs-TAHS", note: "Informal \"tú\" form, for friends and people your age." },
  { cat: "daily", topic: "greet", es: "Bien, gracias. ¿Y usted?", en: "Good, thanks. And you?", pr: "bee-EHN GRAH-see-ahs. ee oos-TEHD" },
  { cat: "daily", topic: "greet", es: "Mucho gusto", en: "Nice to meet you", pr: "MOO-choh GOOS-toh" },
  { cat: "daily", topic: "greet", es: "Me llamo…", en: "My name is…", pr: "meh YAH-moh" },
  { cat: "daily", topic: "polite", es: "Por favor", en: "Please", pr: "por fah-VOR" },
  { cat: "daily", topic: "polite", es: "Muchas gracias", en: "Thank you very much", pr: "MOO-chahs GRAH-see-ahs" },
  { cat: "daily", topic: "polite", es: "De nada", en: "You're welcome", pr: "deh NAH-dah", note: "You'll also hear \"a la orden\" (at your service) and \"para servirle\"." },
  { cat: "daily", topic: "polite", es: "Con permiso", en: "Excuse me (to get past someone)", pr: "kohn pehr-MEE-soh", note: "Also said when leaving a table or a room." },
  { cat: "daily", topic: "polite", es: "Disculpe", en: "Excuse me / Sorry (to get attention)", pr: "dees-KOOL-peh" },
  { cat: "daily", topic: "polite", es: "Perdón", en: "Sorry / Pardon me", pr: "pehr-DOHN" },
  { cat: "daily", topic: "polite", es: "¿Mande?", en: "Pardon? / Sorry, what?", pr: "MAHN-deh", note: "The polite Mexican way to ask someone to repeat. Much nicer than \"¿Qué?\"." },
  { cat: "daily", topic: "casual", es: "Sale", en: "OK / Deal (casual)", pr: "SAH-leh", note: "Very Mexican. \"Va\" and \"órale\" work the same way." },
  { cat: "daily", topic: "understand", es: "No entiendo", en: "I don't understand", pr: "noh ehn-tee-EHN-doh" },
  { cat: "daily", topic: "understand", es: "¿Habla inglés?", en: "Do you speak English?", pr: "AH-blah een-GLEHS" },
  { cat: "daily", topic: "understand", es: "Hablo un poco de español", en: "I speak a little Spanish", pr: "AH-bloh oon POH-koh deh ehs-pah-NYOHL" },
  { cat: "daily", topic: "understand", es: "¿Puede hablar más despacio?", en: "Can you speak more slowly?", pr: "PWEH-deh ah-BLAR mahs dehs-PAH-see-oh" },
  { cat: "daily", topic: "understand", es: "¿Cómo se dice … en español?", en: "How do you say … in Spanish?", pr: "KOH-moh seh DEE-seh … ehn ehs-pah-NYOHL" },
  { cat: "daily", topic: "directions", es: "¿Dónde está el baño?", en: "Where is the bathroom?", pr: "DOHN-deh ehs-TAH ehl BAH-nyoh", note: "Public restrooms often cost 5–10 pesos. Keep coins handy." },
  { cat: "daily", topic: "directions", es: "¿Dónde está…?", en: "Where is…?", pr: "DOHN-deh ehs-TAH" },
  { cat: "daily", topic: "directions", es: "¿Está lejos?", en: "Is it far?", pr: "ehs-TAH LEH-hohs" },
  { cat: "daily", topic: "directions", es: "A la derecha / a la izquierda", en: "To the right / to the left", pr: "ah lah deh-REH-chah / ah lah ees-kee-EHR-dah" },
  { cat: "daily", topic: "directions", es: "Todo derecho", en: "Straight ahead", pr: "TOH-doh deh-REH-choh" },
  { cat: "daily", topic: "directions", es: "¿Cuánto cuesta ir a…?", en: "How much to go to…? (taxi)", pr: "KWAHN-toh KWEHS-tah eer ah", note: "Agree on the fare before you get in if there's no meter." },
  { cat: "daily", topic: "help", es: "¿Qué hora es?", en: "What time is it?", pr: "keh OH-rah ehs" },
  { cat: "daily", topic: "help", es: "Ahorita", en: "Right now / In a little bit", pr: "ah-oh-REE-tah", note: "Famously flexible: can mean this second, in an hour, or maybe never." },
  { cat: "daily", topic: "help", es: "¿Me puede ayudar?", en: "Can you help me?", pr: "meh PWEH-deh ah-yoo-DAR" },
  { cat: "daily", topic: "help", es: "Estoy perdido / perdida", en: "I'm lost (man / woman)", pr: "ehs-TOY pehr-DEE-doh / pehr-DEE-dah" },
  { cat: "daily", topic: "help", es: "¿Hay wifi? ¿Cuál es la contraseña?", en: "Is there wifi? What's the password?", pr: "eye WEE-fee? kwahl ehs lah kohn-trah-SEH-nyah" },
  { cat: "daily", topic: "help", es: "¿Nos puede tomar una foto?", en: "Could you take a photo of us?", pr: "nohs PWEH-deh toh-MAR OO-nah FOH-toh" },
  { cat: "daily", topic: "help", es: "No hay problema", en: "No problem", pr: "noh eye proh-BLEH-mah" },
  { cat: "daily", topic: "casual", es: "¿Qué onda?", en: "What's up? (casual)", pr: "keh OHN-dah" },
  { cat: "daily", topic: "casual", es: "¡Qué padre!", en: "How cool! / Awesome!", pr: "keh PAH-dreh" },
  { cat: "daily", topic: "greet", es: "Nos vemos", en: "See you", pr: "nohs VEH-mohs" },
  { cat: "daily", topic: "greet", es: "Hasta luego", en: "See you later / Bye", pr: "AHS-tah LWEH-goh" },
  { cat: "daily", topic: "greet", es: "¡Que le vaya bien!", en: "Have a good one! (lit. may it go well)", pr: "keh leh VAH-yah bee-EHN" },

  // ---------- Restaurants ----------
  { cat: "food", topic: "seat", es: "Una mesa para dos, por favor", en: "A table for two, please", pr: "OO-nah MEH-sah PAH-rah dohs, por fah-VOR", note: "tres = 3, cuatro = 4, cinco = 5" },
  { cat: "food", topic: "seat", es: "Tengo una reservación a nombre de…", en: "I have a reservation under the name…", pr: "TEHN-goh OO-nah reh-sehr-vah-see-OHN ah NOHM-breh deh" },
  { cat: "food", topic: "seat", es: "¿Tiene mesa afuera?", en: "Do you have a table outside?", pr: "tee-EH-neh MEH-sah ah-FWEH-rah" },
  { cat: "food", topic: "seat", es: "La carta, por favor", en: "The menu, please", pr: "lah KAR-tah, por fah-VOR", note: "\"El menú\" is also understood. \"Menú del día\" / \"comida corrida\" is a cheap set lunch." },
  { cat: "food", topic: "seat", es: "Joven / Señorita", en: "Excuse me (to call the waiter / waitress)", pr: "HOH-vehn / seh-nyoh-REE-tah", note: "\"Joven\" (young man) is used for male servers of any age. Never snap or whistle." },
  { cat: "food", topic: "order", es: "¿Qué me recomienda?", en: "What do you recommend?", pr: "keh meh reh-koh-mee-EHN-dah" },
  { cat: "food", topic: "order", es: "¿Cuál es la especialidad de la casa?", en: "What's the house specialty?", pr: "kwahl ehs lah ehs-peh-see-ah-lee-DAHD deh lah KAH-sah" },
  { cat: "food", topic: "order", es: "Quisiera…", en: "I would like…", pr: "kee-see-EH-rah" },
  { cat: "food", topic: "order", es: "Me da…, por favor", en: "I'll have…, please (lit. give me)", pr: "meh DAH…, por fah-VOR", note: "Sounds blunt in English but is completely normal and polite in Mexico." },
  { cat: "food", topic: "order", es: "¿Me regala una servilleta?", en: "Could I get a napkin?", pr: "meh reh-GAH-lah OO-nah sehr-vee-YEH-tah", note: "\"Regalar\" literally means to gift, but Mexicans use it as a soft, polite \"may I have\"." },
  { cat: "food", topic: "order", es: "¿Me trae…?", en: "Could you bring me…?", pr: "meh TRAH-eh" },
  { cat: "food", topic: "order", es: "Para mí…", en: "For me…", pr: "PAH-rah MEE" },
  { cat: "food", topic: "order", es: "Para aquí", en: "For here (dine in)", pr: "PAH-rah ah-KEE" },
  { cat: "food", topic: "order", es: "Para llevar", en: "To go", pr: "PAH-rah yeh-VAR" },
  { cat: "food", topic: "order", es: "¿De qué tiene?", en: "What fillings do you have? (tacos, tamales…)", pr: "deh KEH tee-EH-neh" },
  { cat: "food", topic: "order", es: "Dos tacos al pastor, por favor", en: "Two al pastor tacos, please", pr: "dohs TAH-kohs ahl pahs-TOR", note: "Al pastor = spit-roasted marinated pork, often with pineapple." },
  { cat: "food", topic: "custom", es: "Con todo", en: "With everything", pr: "kohn TOH-doh", note: "On tacos this usually means onion and cilantro." },
  { cat: "food", topic: "custom", es: "Sin cebolla", en: "Without onion", pr: "seen seh-BOH-yah" },
  { cat: "food", topic: "custom", es: "¿Pica?", en: "Is it spicy?", pr: "PEE-kah", note: "If they say \"poquito\" (a little), assume it's spicy." },
  { cat: "food", topic: "custom", es: "Que no pique, por favor", en: "Not spicy, please", pr: "keh noh PEE-keh, por fah-VOR" },
  { cat: "food", topic: "custom", es: "La salsa aparte, por favor", en: "Sauce on the side, please", pr: "lah SAHL-sah ah-PAR-teh" },
  { cat: "food", topic: "custom", es: "Soy alérgico / alérgica a…", en: "I'm allergic to… (man / woman)", pr: "soy ah-LEHR-hee-koh / ah-LEHR-hee-kah ah", note: "cacahuate = peanut, mariscos = shellfish, nueces = nuts, lácteos = dairy, gluten = gluten" },
  { cat: "food", topic: "custom", es: "Soy vegetariano / vegetariana", en: "I'm vegetarian (man / woman)", pr: "soy veh-heh-tah-ree-AH-noh" },
  { cat: "food", topic: "custom", es: "¿Tiene carne?", en: "Does it have meat?", pr: "tee-EH-neh KAR-neh", note: "Some people don't count chicken or ham as \"carne\". Ask about each: pollo, jamón, manteca (lard)." },
  { cat: "food", topic: "custom", es: "¿Las quesadillas llevan queso?", en: "Do the quesadillas come with cheese?", pr: "lahs keh-sah-DEE-yahs YEH-vahn KEH-soh", note: "In Mexico City they often don't unless you ask!" },
  { cat: "food", topic: "drinks", es: "Una cerveza, por favor", en: "A beer, please", pr: "OO-nah sehr-VEH-sah", note: "Ask \"¿Cuáles tiene?\" to hear what beers they have." },
  { cat: "food", topic: "drinks", es: "Una michelada", en: "A michelada (beer with lime and salt, often spicy sauces)", pr: "OO-nah mee-cheh-LAH-dah", note: "A \"chelada\" is just beer, lime and salt, with no sauces." },
  { cat: "food", topic: "drinks", es: "Un agua natural", en: "A still water", pr: "oon AH-gwah nah-too-RAHL", note: "\"Agua mineral\" is sparkling. \"Agua fresca\" is a fruit drink (jamaica, horchata, tamarindo)." },
  { cat: "food", topic: "drinks", es: "¿El agua es purificada?", en: "Is the water purified?", pr: "ehl AH-gwah ehs poo-ree-fee-KAH-dah", note: "Don't drink tap water. Restaurant ice is normally made from purified water." },
  { cat: "food", topic: "drinks", es: "Sin hielo", en: "No ice", pr: "seen YEH-loh" },
  { cat: "food", topic: "drinks", es: "Un café con leche", en: "A coffee with milk", pr: "oon kah-FEH kohn LEH-cheh", note: "\"Café de olla\" is sweet, cinnamon-spiced coffee. Worth trying." },
  { cat: "food", topic: "drinks", es: "Otra, por favor", en: "Another one, please", pr: "OH-trah, por fah-VOR", note: "Use \"otro\" for a masculine thing (otro café, otro taco)." },
  { cat: "food", topic: "meal", es: "Todo bien, gracias", en: "Everything's good, thanks", pr: "TOH-doh bee-EHN, GRAH-see-ahs" },
  { cat: "food", topic: "meal", es: "¡Está muy rico!", en: "It's delicious!", pr: "ehs-TAH mooy REE-koh" },
  { cat: "food", topic: "meal", es: "¡Provecho!", en: "Enjoy your meal!", pr: "proh-VEH-choh", note: "Mexicans say it to other diners when passing their table or leaving the restaurant." },
  { cat: "food", topic: "pay", es: "La cuenta, por favor", en: "The check, please", pr: "lah KWEHN-tah, por fah-VOR", note: "It won't come until you ask. You can also mime signing in the air." },
  { cat: "food", topic: "pay", es: "¿Aceptan tarjeta?", en: "Do you take cards?", pr: "ah-SEHP-tahn tar-HEH-tah", note: "Many taquerías and markets are cash only." },
  { cat: "food", topic: "pay", es: "¿Me trae la terminal?", en: "Can you bring the card machine?", pr: "meh TRAH-eh lah tehr-mee-NAHL", note: "The card reader comes to your table. Your card shouldn't leave your sight." },
  { cat: "food", topic: "pay", es: "¿Está incluida la propina?", en: "Is the tip included?", pr: "ehs-TAH een-kloo-EE-dah lah proh-PEE-nah", note: "10–15% is standard at sit-down restaurants. Check the bill for \"servicio incluido\"." },
  { cat: "food", topic: "pay", es: "¿Podemos pagar por separado?", en: "Can we pay separately?", pr: "poh-DEH-mohs pah-GAR por seh-pah-RAH-doh" },
  { cat: "food", topic: "pay", es: "¿Dónde se paga?", en: "Where do I pay?", pr: "DOHN-deh seh PAH-gah", note: "At street stalls you usually pay at the end. Tell them what you ate." },

  // ---------- Stores ----------
  { cat: "store", topic: "price", es: "¿Cuánto cuesta?", en: "How much does it cost?", pr: "KWAHN-toh KWEHS-tah" },
  { cat: "store", topic: "price", es: "¿Cuánto es?", en: "How much is it? (total)", pr: "KWAHN-toh EHS" },
  { cat: "store", topic: "price", es: "¿Cuánto le debo?", en: "What do I owe you?", pr: "KWAHN-toh leh DEH-boh" },
  { cat: "store", topic: "price", kind: "hear", es: "Son ciento cincuenta pesos", en: "That's 150 pesos", pr: "sohn see-EHN-toh seen-KWEHN-tah PEH-sohs", note: "20 veinte · 50 cincuenta · 100 cien · 200 doscientos · 500 quinientos · 1,000 mil" },
  { cat: "store", topic: "find", es: "¿Tiene…?", en: "Do you have…?", pr: "tee-EH-neh" },
  { cat: "store", topic: "find", es: "Estoy buscando…", en: "I'm looking for…", pr: "ehs-TOY boos-KAHN-doh" },
  { cat: "store", topic: "find", es: "¿Dónde encuentro…?", en: "Where can I find…?", pr: "DOHN-deh ehn-KWEHN-troh" },
  { cat: "store", topic: "find", es: "Solo estoy viendo, gracias", en: "I'm just looking, thanks", pr: "SOH-loh ehs-TOY vee-EHN-doh, GRAH-see-ahs" },
  { cat: "store", topic: "sizes", es: "¿Me lo puedo probar?", en: "Can I try it on?", pr: "meh loh PWEH-doh proh-BAR" },
  { cat: "store", topic: "sizes", es: "¿Tiene otra talla?", en: "Do you have another size?", pr: "tee-EH-neh OH-trah TAH-yah" },
  { cat: "store", topic: "sizes", es: "Más grande / más chico", en: "Bigger / smaller", pr: "mahs GRAHN-deh / mahs CHEE-koh", note: "Mexico says \"chico\" far more than \"pequeño\"." },
  { cat: "store", topic: "sizes", es: "¿Lo tiene en otro color?", en: "Do you have it in another color?", pr: "loh tee-EH-neh ehn OH-troh koh-LOR" },
  { cat: "store", topic: "sizes", es: "Me lo llevo", en: "I'll take it", pr: "meh loh YEH-voh", note: "\"Me la llevo\" for a feminine thing (la camisa, la bolsa)." },
  { cat: "store", topic: "price", es: "Está muy caro", en: "It's very expensive", pr: "ehs-TAH mooy KAH-roh" },
  { cat: "store", topic: "price", es: "¿Me hace un descuento?", en: "Can you give me a discount?", pr: "meh AH-seh oon dehs-KWEHN-toh", note: "Fine at markets and with street vendors. Not in chain stores or supermarkets." },
  { cat: "store", topic: "price", es: "¿Es lo menos?", en: "Is that your best price?", pr: "ehs loh MEH-nohs", note: "The classic market bargaining line. Keep it friendly." },
  { cat: "store", topic: "pay", es: "¿Puedo pagar con tarjeta?", en: "Can I pay by card?", pr: "PWEH-doh pah-GAR kohn tar-HEH-tah" },
  { cat: "store", topic: "pay", kind: "hear", es: "Solo efectivo", en: "Cash only", pr: "SOH-loh eh-fehk-TEE-voh", note: "A sign you'll see often." },
  { cat: "store", topic: "pay", es: "¿Aceptan dólares?", en: "Do you accept dollars?", pr: "ah-SEHP-tahn DOH-lah-rehs", note: "Paying in pesos almost always gets you a better rate." },
  { cat: "store", topic: "pay", es: "¿Tiene cambio de quinientos?", en: "Do you have change for a 500?", pr: "tee-EH-neh KAHM-bee-oh deh kee-nee-EHN-tohs", note: "Small shops and taxis often can't break big bills. Carry 20s, 50s and coins." },
  { cat: "store", topic: "pay", es: "No traigo cambio", en: "I don't have change / small bills", pr: "noh TRY-goh KAHM-bee-oh", note: "You'll also hear \"feria\", Mexican slang for small change." },
  { cat: "store", topic: "register", es: "¿Me cobra, por favor?", en: "Can you ring me up, please?", pr: "meh KOH-brah, por fah-VOR" },
  { cat: "store", topic: "register", kind: "hear", es: "¿Algo más?", en: "Anything else?", pr: "AHL-goh MAHS", note: "You'll hear this at every register." },
  { cat: "store", topic: "register", es: "Es todo, gracias", en: "That's all, thanks", pr: "ehs TOH-doh, GRAH-see-ahs" },
  { cat: "store", topic: "register", kind: "hear", es: "¿Redondea?", en: "Would you like to round up? (to donate)", pr: "reh-dohn-DEH-ah", note: "Cashiers at OXXO and supermarkets ask this. \"No, gracias\" is perfectly fine." },
  { cat: "store", topic: "register", es: "¿Me da una bolsa?", en: "Can I have a bag?", pr: "meh DAH OO-nah BOHL-sah", note: "Many states ban free plastic bags, so bring your own tote." },
  { cat: "store", topic: "register", es: "No necesito bolsa, gracias", en: "I don't need a bag, thanks", pr: "noh neh-seh-SEE-toh BOHL-sah" },
  { cat: "store", topic: "register", es: "¿Me da el ticket?", en: "Can I have the receipt?", pr: "meh DAH ehl TEE-keht", note: "\"Ticket\" is the everyday word for a receipt." },
  { cat: "store", topic: "errands", es: "Un kilo de…, por favor", en: "A kilo of…, please", pr: "oon KEE-loh deh", note: "Produce and meat are sold by the kilo (about 2.2 lb). \"Medio kilo\" = half, \"un cuarto\" = a quarter." },
  { cat: "store", topic: "errands", es: "¿Está fresco?", en: "Is it fresh?", pr: "ehs-TAH FREHS-koh" },
  { cat: "store", topic: "errands", es: "¿Tiene algo para…?", en: "Do you have something for…? (pharmacy)", pr: "tee-EH-neh AHL-goh PAH-rah", note: "…el dolor de cabeza (headache), …la diarrea, …las quemaduras de sol (sunburn), …la tos (cough)" },
  { cat: "store", topic: "errands", es: "Una recarga de cien pesos, por favor", en: "A 100-peso phone top-up, please", pr: "OO-nah reh-KAR-gah deh see-EHN PEH-sohs", note: "Top up prepaid SIMs (Telcel, AT&T) at any OXXO. Tell them the carrier and your number." },
  { cat: "store", topic: "errands", es: "¿Dónde hay un cajero?", en: "Where is there an ATM?", pr: "DOHN-deh eye oon kah-HEH-roh", note: "Use ATMs inside bank branches. Decline the ATM's own currency conversion." },
  { cat: "store", topic: "errands", es: "¿A qué hora cierran?", en: "What time do you close?", pr: "ah keh OH-rah see-EH-rrahn", note: "\"¿A qué hora abren?\" = What time do you open?" },
  { cat: "store", topic: "errands", es: "¿Me lo envuelve para regalo?", en: "Can you gift-wrap it?", pr: "meh loh ehn-VWEHL-veh PAH-rah reh-GAH-loh" },

  // ---------- Garden center (vivero) ----------
  // Water
  { cat: "garden", topic: "water", es: "¿Cada cuánto se riega?", en: "How often do I water it?", pr: "KAH-dah KWAHN-toh seh ree-EH-gah" },
  { cat: "garden", topic: "water", es: "¿Cuánta agua necesita?", en: "How much water does it need?", pr: "KWAHN-tah AH-gwah neh-seh-SEE-tah" },
  { cat: "garden", topic: "water", es: "¿Necesita mucha agua o poca?", en: "Does it need a lot of water or a little?", pr: "neh-seh-SEE-tah MOO-chah AH-gwah oh POH-kah" },
  { cat: "garden", topic: "water", es: "¿Hay que dejar que se seque la tierra?", en: "Should I let the soil dry out between waterings?", pr: "eye keh deh-HAR keh seh SEH-keh lah tee-EH-rrah" },
  { cat: "garden", topic: "water", es: "¿Aguanta la sequía?", en: "Does it tolerate drought?", pr: "ah-GWAHN-tah lah seh-KEE-ah" },
  { cat: "garden", topic: "water", es: "¿Le gusta la humedad?", en: "Does it like humidity?", pr: "leh GOOS-tah lah oo-meh-DAHD" },
  { cat: "garden", topic: "water", es: "¿Es mejor regar en la mañana o en la tarde?", en: "Is it better to water in the morning or the evening?", pr: "ehs meh-HOR reh-GAR ehn lah mah-NYAH-nah oh ehn lah TAR-deh" },
  { cat: "garden", topic: "water", es: "¿Cuánto riego necesita en temporada de lluvias?", en: "How much watering during the rainy season?", pr: "KWAHN-toh ree-EH-goh neh-seh-SEE-tah ehn tehm-poh-RAH-dah deh YOO-vee-ahs" },
  { cat: "garden", topic: "water", kind: "hear", es: "Riego diario", en: "Water it every day", pr: "ree-EH-goh dee-AH-ree-oh" },
  { cat: "garden", topic: "water", kind: "hear", es: "Cada tercer día", en: "Every other day", pr: "KAH-dah tehr-SEHR DEE-ah", note: "Very common in Mexico. Literally “every third day”, but it means every other day." },
  { cat: "garden", topic: "water", kind: "hear", es: "Una o dos veces por semana", en: "Once or twice a week", pr: "OO-nah oh dohs VEH-sehs por seh-MAH-nah" },
  { cat: "garden", topic: "water", kind: "hear", es: "Cuando la tierra esté seca", en: "When the soil is dry", pr: "KWAHN-doh lah tee-EH-rrah ehs-TEH SEH-kah", note: "Push a finger into the soil. If it's dry a couple of centimeters down, it's time." },
  { cat: "garden", topic: "water", kind: "hear", es: "Poquita agua", en: "Just a little water", pr: "poh-KEE-tah AH-gwah" },
  { cat: "garden", topic: "water", kind: "hear", es: "No la encharque", en: "Don't overwater it / don't let it sit in water", pr: "noh lah ehn-CHAR-keh", note: "Encharcar = to waterlog." },
  { cat: "garden", topic: "water", kind: "hear", es: "Se le pudre la raíz", en: "The roots rot", pr: "seh leh POO-dreh lah rah-EES", note: "What happens with too much water." },
  { cat: "garden", topic: "water", kind: "word", es: "regar", en: "to water", pr: "reh-GAR" },
  { cat: "garden", topic: "water", kind: "word", es: "el riego", en: "watering", pr: "ehl ree-EH-goh" },
  { cat: "garden", topic: "water", kind: "word", es: "seco / húmedo", en: "dry / moist", pr: "SEH-koh / OO-meh-doh" },
  { cat: "garden", topic: "water", kind: "word", es: "el drenaje", en: "drainage", pr: "ehl dreh-NAH-heh" },

  // Light
  { cat: "garden", topic: "light", es: "¿Necesita sol directo?", en: "Does it need direct sun?", pr: "neh-seh-SEE-tah sohl dee-REHK-toh" },
  { cat: "garden", topic: "light", es: "¿Cuántas horas de sol necesita?", en: "How many hours of sun does it need?", pr: "KWAHN-tahs OH-rahs deh sohl neh-seh-SEE-tah" },
  { cat: "garden", topic: "light", es: "¿Aguanta el sol todo el día?", en: "Can it take sun all day?", pr: "ah-GWAHN-tah ehl sohl TOH-doh ehl DEE-ah" },
  { cat: "garden", topic: "light", es: "¿Se puede tener en la sombra?", en: "Can it live in the shade?", pr: "seh PWEH-deh teh-NEHR ehn lah SOHM-brah" },
  { cat: "garden", topic: "light", es: "¿Es de interior o de exterior?", en: "Is it an indoor or outdoor plant?", pr: "ehs deh een-teh-ree-OR oh deh ehks-teh-ree-OR" },
  { cat: "garden", topic: "light", es: "¿Sirve para adentro, con poca luz?", en: "Will it work indoors with little light?", pr: "SEER-veh PAH-rah ah-DEHN-troh, kohn POH-kah loos" },
  { cat: "garden", topic: "light", es: "Donde la quiero poner le da sol de la tarde", en: "Where I want to put it gets afternoon sun", pr: "DOHN-deh lah kee-EH-roh poh-NEHR leh dah sohl deh lah TAR-deh", note: "Swap in “de la mañana” for morning sun." },
  { cat: "garden", topic: "light", kind: "hear", es: "Pleno sol / sol directo", en: "Full sun / direct sun", pr: "PLEH-noh sohl / sohl dee-REHK-toh" },
  { cat: "garden", topic: "light", kind: "hear", es: "Media sombra", en: "Partial shade", pr: "MEH-dee-ah SOHM-brah", note: "Sun for part of the day, or filtered sun under trees." },
  { cat: "garden", topic: "light", kind: "hear", es: "Sombra", en: "Shade", pr: "SOHM-brah" },
  { cat: "garden", topic: "light", kind: "hear", es: "Luz indirecta", en: "Indirect light", pr: "loos een-dee-REHK-tah", note: "Bright room, but out of the sun's direct rays." },
  { cat: "garden", topic: "light", kind: "hear", es: "Nada más sol de la mañana", en: "Morning sun only", pr: "NAH-dah mahs sohl deh lah mah-NYAH-nah" },
  { cat: "garden", topic: "light", kind: "hear", es: "Se quema con el sol", en: "It gets sunburned", pr: "seh KEH-mah kohn ehl sohl" },
  { cat: "garden", topic: "light", kind: "word", es: "el sol", en: "sun", pr: "ehl sohl" },
  { cat: "garden", topic: "light", kind: "word", es: "la sombra", en: "shade", pr: "lah SOHM-brah" },
  { cat: "garden", topic: "light", kind: "word", es: "la luz", en: "light", pr: "lah loos" },
  { cat: "garden", topic: "light", kind: "word", es: "adentro / afuera", en: "inside / outside", pr: "ah-DEHN-troh / ah-FWEH-rah" },

  // Soil & fertilizer
  { cat: "garden", topic: "soil", es: "¿Qué tierra le pongo?", en: "What soil should I use for it?", pr: "keh tee-EH-rrah leh POHN-goh" },
  { cat: "garden", topic: "soil", es: "¿Tiene tierra para macetas?", en: "Do you have potting soil?", pr: "tee-EH-neh tee-EH-rrah PAH-rah mah-SEH-tahs" },
  { cat: "garden", topic: "soil", es: "¿Necesita buen drenaje?", en: "Does it need good drainage?", pr: "neh-seh-SEE-tah bwehn dreh-NAH-heh" },
  { cat: "garden", topic: "soil", es: "¿Qué abono le pongo, y cada cuánto?", en: "What fertilizer should I use, and how often?", pr: "keh ah-BOH-noh leh POHN-goh, ee KAH-dah KWAHN-toh" },
  { cat: "garden", topic: "soil", es: "¿Tiene composta?", en: "Do you have compost?", pr: "tee-EH-neh kohm-POHS-tah" },
  { cat: "garden", topic: "soil", es: "¿Lo vende por bulto o suelto?", en: "Do you sell it by the sack or loose?", pr: "loh VEHN-deh por BOOL-toh oh SWEHL-toh" },
  { cat: "garden", topic: "soil", kind: "hear", es: "Una vez al mes", en: "Once a month", pr: "OO-nah vehs ahl mehs" },
  { cat: "garden", topic: "soil", kind: "hear", es: "Revuélvala con tezontle", en: "Mix it with volcanic gravel", pr: "reh-VWEHL-vah-lah kohn teh-SOHN-tleh" },
  { cat: "garden", topic: "soil", kind: "word", es: "la tierra", en: "soil / dirt", pr: "lah tee-EH-rrah" },
  { cat: "garden", topic: "soil", kind: "word", es: "tierra de hoja", en: "leaf-mold soil", pr: "tee-EH-rrah deh OH-hah", note: "Dark composted-leaf soil sold at almost every Mexican vivero." },
  { cat: "garden", topic: "soil", kind: "word", es: "tierra negra", en: "dark topsoil", pr: "tee-EH-rrah NEH-grah" },
  { cat: "garden", topic: "soil", kind: "word", es: "el tezontle", en: "red volcanic gravel (for drainage)", pr: "ehl teh-SOHN-tleh", note: "Mixed in or layered at the bottom of pots for drainage." },
  { cat: "garden", topic: "soil", kind: "word", es: "el abono / el fertilizante", en: "fertilizer", pr: "ehl ah-BOH-noh / ehl fehr-tee-lee-SAHN-teh" },
  { cat: "garden", topic: "soil", kind: "word", es: "la composta", en: "compost", pr: "lah kohm-POHS-tah" },
  { cat: "garden", topic: "soil", kind: "word", es: "humus de lombriz", en: "worm castings", pr: "OO-moos deh lohm-BREES" },
  { cat: "garden", topic: "soil", kind: "word", es: "la arena", en: "sand", pr: "lah ah-REH-nah" },
  { cat: "garden", topic: "soil", kind: "word", es: "el bulto", en: "sack (of soil etc.)", pr: "ehl BOOL-toh" },

  // Pots & planting
  { cat: "garden", topic: "pots", es: "¿De qué tamaño de maceta la necesita?", en: "What size pot does it need?", pr: "deh keh tah-MAH-nyoh deh mah-SEH-tah lah neh-seh-SEE-tah" },
  { cat: "garden", topic: "pots", es: "¿La maceta tiene hoyo para el drenaje?", en: "Does the pot have a drainage hole?", pr: "lah mah-SEH-tah tee-EH-neh OH-yoh PAH-rah ehl dreh-NAH-heh" },
  { cat: "garden", topic: "pots", es: "¿Hay que trasplantarla?", en: "Does it need to be repotted?", pr: "eye keh trahs-plahn-TAR-lah" },
  { cat: "garden", topic: "pots", es: "¿Me la pueden trasplantar aquí?", en: "Can you repot it for me here?", pr: "meh lah PWEH-dehn trahs-plahn-TAR ah-KEE", note: "Many viveros will, often free if you buy the pot and soil there." },
  { cat: "garden", topic: "pots", es: "¿Se puede sembrar en el suelo?", en: "Can it be planted in the ground?", pr: "seh PWEH-deh sehm-BRAR ehn ehl SWEH-loh" },
  { cat: "garden", topic: "pots", es: "¿A qué distancia se siembran?", en: "How far apart do you plant them?", pr: "ah keh dees-TAHN-see-ah seh see-EHM-brahn" },
  { cat: "garden", topic: "pots", kind: "word", es: "la maceta", en: "pot / planter", pr: "lah mah-SEH-tah" },
  { cat: "garden", topic: "pots", kind: "word", es: "el plato", en: "saucer (under the pot)", pr: "ehl PLAH-toh" },
  { cat: "garden", topic: "pots", kind: "word", es: "de barro", en: "terracotta / clay", pr: "deh BAH-rroh" },
  { cat: "garden", topic: "pots", kind: "word", es: "colgante", en: "hanging", pr: "kohl-GAHN-teh" },
  { cat: "garden", topic: "pots", kind: "word", es: "sembrar / plantar", en: "to plant", pr: "sehm-BRAR / plahn-TAR" },
  { cat: "garden", topic: "pots", kind: "word", es: "trasplantar", en: "to repot / transplant", pr: "trahs-plahn-TAR" },

  // Size & growth
  { cat: "garden", topic: "size", es: "¿Qué tan grande se pone?", en: "How big does it get?", pr: "keh tahn GRAHN-deh seh POH-neh" },
  { cat: "garden", topic: "size", es: "¿Qué tan alta crece?", en: "How tall does it grow?", pr: "keh tahn AHL-tah KREH-seh" },
  { cat: "garden", topic: "size", es: "¿Crece rápido o lento?", en: "Does it grow fast or slow?", pr: "KREH-seh RAH-pee-doh oh LEHN-toh" },
  { cat: "garden", topic: "size", es: "¿Hay que podarla?", en: "Does it need pruning?", pr: "eye keh poh-DAR-lah" },
  { cat: "garden", topic: "size", es: "¿Las raíces son agresivas?", en: "Are the roots invasive?", pr: "lahs rah-EE-sehs sohn ah-greh-SEE-vahs", note: "Ask before planting a tree near a wall, pool or pipes." },
  { cat: "garden", topic: "size", es: "¿Dura todo el año?", en: "Does it last all year? (perennial)", pr: "DOO-rah TOH-doh ehl AH-nyoh" },
  { cat: "garden", topic: "size", kind: "hear", es: "Es de temporada", en: "It's seasonal (won't last)", pr: "ehs deh tehm-poh-RAH-dah" },
  { cat: "garden", topic: "size", kind: "hear", es: "Llega a medir dos metros", en: "It gets up to two meters", pr: "YEH-gah ah meh-DEER dohs MEH-trohs", note: "1 metro ≈ 3.3 feet." },

  // Climate & location
  { cat: "garden", topic: "climate", es: "¿Se da bien aquí?", en: "Does it do well here?", pr: "seh dah bee-EHN ah-KEE", note: "The single most useful question: the staff know what survives locally." },
  { cat: "garden", topic: "climate", es: "¿Aguanta el calor?", en: "Can it take the heat?", pr: "ah-GWAHN-tah ehl kah-LOR" },
  { cat: "garden", topic: "climate", es: "¿Aguanta la brisa del mar?", en: "Can it handle the sea breeze and salt?", pr: "ah-GWAHN-tah lah BREE-sah dehl mar", note: "Near the beach, ask this first. Salt spray burns many plants." },
  { cat: "garden", topic: "climate", es: "¿Aguanta el viento?", en: "Can it take wind?", pr: "ah-GWAHN-tah ehl vee-EHN-toh" },
  { cat: "garden", topic: "climate", es: "¿Es una planta de la región?", en: "Is it native to the area?", pr: "ehs OO-nah PLAHN-tah deh lah reh-hee-OHN" },
  { cat: "garden", topic: "climate", es: "Es para una terraza cerca del mar", en: "It's for a terrace near the sea", pr: "ehs PAH-rah OO-nah teh-RRAH-sah SEHR-kah dehl mar" },

  // Pests & problems
  { cat: "garden", topic: "pests", es: "Mi planta tiene las hojas amarillas", en: "My plant has yellow leaves", pr: "mee PLAHN-tah tee-EH-neh lahs OH-hahs ah-mah-REE-yahs" },
  { cat: "garden", topic: "pests", es: "Las hojas se están secando", en: "The leaves are drying out", pr: "lahs OH-hahs seh ehs-TAHN seh-KAHN-doh" },
  { cat: "garden", topic: "pests", es: "Tiene bichitos", en: "It has little bugs", pr: "tee-EH-neh bee-CHEE-tohs", note: "Show them a photo on your phone. It beats describing it." },
  { cat: "garden", topic: "pests", es: "¿Qué le puedo poner?", en: "What can I put on it?", pr: "keh leh PWEH-doh poh-NEHR" },
  { cat: "garden", topic: "pests", es: "¿Tiene algo orgánico?", en: "Do you have something organic?", pr: "tee-EH-neh AHL-goh or-GAH-nee-koh" },
  { cat: "garden", topic: "pests", es: "¿Tiene algo para las hormigas?", en: "Do you have something for ants?", pr: "tee-EH-neh AHL-goh PAH-rah lahs or-MEE-gahs", note: "Leafcutter ants (hormiga arriera) can strip a plant overnight." },
  { cat: "garden", topic: "pests", kind: "word", es: "la plaga", en: "pest / infestation", pr: "lah PLAH-gah" },
  { cat: "garden", topic: "pests", kind: "word", es: "el hongo", en: "fungus", pr: "ehl OHN-goh" },
  { cat: "garden", topic: "pests", kind: "word", es: "la cochinilla", en: "mealybug / scale", pr: "lah koh-chee-NEE-yah" },
  { cat: "garden", topic: "pests", kind: "word", es: "la mosca blanca", en: "whitefly", pr: "lah MOHS-kah BLAHN-kah" },
  { cat: "garden", topic: "pests", kind: "word", es: "el pulgón", en: "aphid", pr: "ehl pool-GOHN" },
  { cat: "garden", topic: "pests", kind: "word", es: "aceite de neem", en: "neem oil", pr: "ah-SAY-teh deh neem" },

  // Pets & kids
  { cat: "garden", topic: "safety", es: "¿Es tóxica para perros o gatos?", en: "Is it toxic to dogs or cats?", pr: "ehs TOHK-see-kah PAH-rah PEH-rrohs oh GAH-tohs" },
  { cat: "garden", topic: "safety", es: "¿Es segura para niños?", en: "Is it safe for kids?", pr: "ehs seh-GOO-rah PAH-rah NEE-nyohs" },
  { cat: "garden", topic: "safety", es: "¿Tiene espinas?", en: "Does it have thorns / spines?", pr: "tee-EH-neh ehs-PEE-nahs" },
  { cat: "garden", topic: "safety", es: "¿La savia irrita la piel?", en: "Does the sap irritate skin?", pr: "lah SAH-vee-ah ee-RREE-tah lah pee-EHL" },

  // Flowers & fruit
  { cat: "garden", topic: "bloom", es: "¿Cuándo florea?", en: "When does it flower?", pr: "KWAHN-doh floh-REH-ah", note: "“Florece” is also correct; “florea” is what you'll usually hear in Mexico." },
  { cat: "garden", topic: "bloom", es: "¿De qué color es la flor?", en: "What color is the flower?", pr: "deh keh koh-LOR ehs lah flor" },
  { cat: "garden", topic: "bloom", es: "¿Da fruto? ¿En cuánto tiempo?", en: "Does it bear fruit? How long until it does?", pr: "dah FROO-toh? ehn KWAHN-toh tee-EHM-poh" },
  { cat: "garden", topic: "bloom", es: "¿Necesita otra para dar fruto?", en: "Does it need a second plant to fruit?", pr: "neh-seh-SEE-tah OH-trah PAH-rah dar FROO-toh" },
  { cat: "garden", topic: "bloom", es: "¿Atrae colibríes o mariposas?", en: "Does it attract hummingbirds or butterflies?", pr: "ah-TRAH-eh koh-lee-BREE-ehs oh mah-ree-POH-sahs" },
  { cat: "garden", topic: "bloom", es: "¿Huele?", en: "Is it fragrant? (lit. does it smell?)", pr: "WEH-leh" },

  // Finding plants
  { cat: "garden", topic: "find", es: "Busco una planta para…", en: "I'm looking for a plant for…", pr: "BOOS-koh OO-nah PLAHN-tah PAH-rah" },
  { cat: "garden", topic: "find", es: "¿Cómo se llama esta planta?", en: "What's this plant called?", pr: "KOH-moh seh YAH-mah EHS-tah PLAHN-tah" },
  { cat: "garden", topic: "find", es: "Quiero algo que no necesite mucho cuidado", en: "I want something low-maintenance", pr: "kee-EH-roh AHL-goh keh noh neh-seh-SEE-teh MOO-choh kwee-DAH-doh" },
  { cat: "garden", topic: "find", es: "¿Tienen plantas de sombra?", en: "Do you have shade plants?", pr: "tee-EH-nehn PLAHN-tahs deh SOHM-brah" },
  { cat: "garden", topic: "find", es: "¿Tienen árboles frutales?", en: "Do you have fruit trees?", pr: "tee-EH-nehn AR-boh-lehs froo-TAH-lehs" },
  { cat: "garden", topic: "find", es: "¿Tienen semillas de…?", en: "Do you have seeds for…?", pr: "tee-EH-nehn seh-MEE-yahs deh" },
  { cat: "garden", topic: "find", es: "¿Tienen más grandes / más chicas?", en: "Do you have bigger / smaller ones?", pr: "tee-EH-nehn mahs GRAHN-dehs / mahs CHEE-kahs" },
  { cat: "garden", topic: "find", es: "¿Me la puede apartar?", en: "Can you set it aside for me?", pr: "meh lah PWEH-deh ah-par-TAR" },

  // Buying & delivery
  { cat: "garden", topic: "buy", es: "¿Cuánto cuesta esta?", en: "How much is this one?", pr: "KWAHN-toh KWEHS-tah EHS-tah" },
  { cat: "garden", topic: "buy", es: "¿Me hace descuento si llevo varias?", en: "Any discount if I take several?", pr: "meh AH-seh dehs-KWEHN-toh see YEH-voh VAH-ree-ahs" },
  { cat: "garden", topic: "buy", es: "¿Hacen entregas a domicilio?", en: "Do you deliver?", pr: "AH-sehn ehn-TREH-gahs ah doh-mee-SEE-lee-oh" },
  { cat: "garden", topic: "buy", es: "¿Cuánto cobran por llevarlo a…?", en: "How much to deliver it to…?", pr: "KWAHN-toh KOH-brahn por yeh-VAR-loh ah" },
  { cat: "garden", topic: "buy", es: "¿Me ayuda a subirla al carro?", en: "Can you help me load it into the car?", pr: "meh ah-YOO-dah ah soo-BEER-lah ahl KAH-rroh" },
  { cat: "garden", topic: "buy", es: "¿Aceptan tarjeta o solo efectivo?", en: "Do you take cards or cash only?", pr: "ah-SEHP-tahn tar-HEH-tah oh SOH-loh eh-fehk-TEE-voh" },
  { cat: "garden", topic: "buy", es: "¿Tienen garantía si se muere?", en: "Is there a guarantee if it dies?", pr: "tee-EH-nehn gah-rahn-TEE-ah see seh MWEH-reh", note: "Most don't, but it's fair to ask on trees and big plants." },

  // Tools & supplies
  { cat: "garden", topic: "tools", es: "¿Dónde están las herramientas?", en: "Where are the tools?", pr: "DOHN-deh ehs-TAHN lahs eh-rrah-mee-EHN-tahs" },
  { cat: "garden", topic: "tools", kind: "word", es: "la manguera", en: "hose", pr: "lah mahn-GEH-rah" },
  { cat: "garden", topic: "tools", kind: "word", es: "la regadera", en: "watering can", pr: "lah reh-gah-DEH-rah" },
  { cat: "garden", topic: "tools", kind: "word", es: "el aspersor", en: "sprinkler", pr: "ehl ahs-pehr-SOR" },
  { cat: "garden", topic: "tools", kind: "word", es: "riego por goteo", en: "drip irrigation", pr: "ree-EH-goh por goh-TEH-oh" },
  { cat: "garden", topic: "tools", kind: "word", es: "las tijeras de podar", en: "pruning shears", pr: "lahs tee-HEH-rahs deh poh-DAR" },
  { cat: "garden", topic: "tools", kind: "word", es: "la pala", en: "shovel", pr: "lah PAH-lah" },
  { cat: "garden", topic: "tools", kind: "word", es: "la palita", en: "hand trowel", pr: "lah pah-LEE-tah" },
  { cat: "garden", topic: "tools", kind: "word", es: "el rastrillo", en: "rake", pr: "ehl rahs-TREE-yoh" },
  { cat: "garden", topic: "tools", kind: "word", es: "los guantes", en: "gloves", pr: "lohs GWAHN-tehs" },
  { cat: "garden", topic: "tools", kind: "word", es: "la malla sombra", en: "shade cloth", pr: "lah MAH-yah SOHM-brah" },

  // Kinds of plants
  { cat: "garden", topic: "kinds", kind: "word", es: "la palma", en: "palm", pr: "lah PAHL-mah" },
  { cat: "garden", topic: "kinds", kind: "word", es: "la suculenta", en: "succulent", pr: "lah soo-koo-LEHN-tah" },
  { cat: "garden", topic: "kinds", kind: "word", es: "el cactus", en: "cactus", pr: "ehl KAHK-toos" },
  { cat: "garden", topic: "kinds", kind: "word", es: "el helecho", en: "fern", pr: "ehl eh-LEH-choh" },
  { cat: "garden", topic: "kinds", kind: "word", es: "la enredadera", en: "climbing vine", pr: "lah ehn-reh-dah-DEH-rah" },
  { cat: "garden", topic: "kinds", kind: "word", es: "la bugambilia", en: "bougainvillea", pr: "lah boo-gahm-BEE-lee-ah" },
  { cat: "garden", topic: "kinds", kind: "word", es: "el arbusto", en: "shrub", pr: "ehl ar-BOOS-toh" },
  { cat: "garden", topic: "kinds", kind: "word", es: "el seto", en: "hedge", pr: "ehl SEH-toh" },
  { cat: "garden", topic: "kinds", kind: "word", es: "el árbol frutal", en: "fruit tree", pr: "ehl AR-bohl froo-TAHL" },
  { cat: "garden", topic: "kinds", kind: "word", es: "el pasto", en: "lawn grass", pr: "ehl PAHS-toh" },
  { cat: "garden", topic: "kinds", kind: "word", es: "el cubresuelo", en: "ground cover", pr: "ehl koo-breh-SWEH-loh" },
  { cat: "garden", topic: "kinds", kind: "word", es: "hierbas de olor", en: "cooking herbs", pr: "YEHR-bahs deh oh-LOR" },
  { cat: "garden", topic: "kinds", kind: "word", es: "la albahaca", en: "basil", pr: "lah ahl-bah-AH-kah" },
  { cat: "garden", topic: "kinds", kind: "word", es: "la planta de ornato", en: "ornamental plant", pr: "lah PLAHN-tah deh or-NAH-toh" },

  // ---------- Gas station ----------
  // Filling up
  { cat: "gas", topic: "fill", es: "Lleno, por favor.", en: "Fill it up, please.", pr: "YEH-noh, por fah-VOR", note: "In Mexico an attendant pumps the gas for you. Stay in the car and tell them what you want." },
  { cat: "gas", topic: "fill", es: "Quinientos pesos de magna, por favor.", en: "500 pesos of regular, please.", pr: "kee-nee-EHN-tohs PEH-sohs deh MAHG-nah, por fah-VOR", note: "Magna = regular (green pump). Premium = red pump. Diésel = black pump." },
  { cat: "gas", topic: "fill", es: "Doscientos de premium.", en: "200 pesos of premium.", pr: "dohs-see-EHN-tohs deh PREH-mee-oom" },
  { cat: "gas", topic: "fill", es: "¿Me puede mostrar que está en ceros?", en: "Can you show me the pump is at zero?", pr: "meh PWEH-deh mohs-TRAR keh ehs-TAH ehn SEH-rohs", note: "Look at the pump before they start. The most common trick is starting from the last customer's total." },
  { cat: "gas", topic: "fill", es: "¿Está en ceros?", en: "Is it at zero?", pr: "ehs-TAH ehn SEH-rohs" },
  { cat: "gas", topic: "fill", es: "¿Cuál es la magna?", en: "Which one is regular?", pr: "kwahl ehs lah MAHG-nah" },
  { cat: "gas", topic: "fill", es: "El tanque está de este lado.", en: "The gas cap is on this side.", pr: "ehl TAHN-keh ehs-TAH deh EHS-teh LAH-doh" },
  { cat: "gas", topic: "fill", es: "Es un coche rentado.", en: "It's a rental car.", pr: "ehs oon KOH-cheh rehn-TAH-doh" },
  { cat: "gas", topic: "fill", kind: "hear", es: "¿Cuánto le cargo?", en: "How much should I put in?", pr: "KWAHN-toh leh KAR-goh" },
  { cat: "gas", topic: "fill", kind: "hear", es: "¿Lleno?", en: "Fill it up?", pr: "YEH-noh" },
  { cat: "gas", topic: "fill", kind: "hear", es: "¿Magna o premium?", en: "Regular or premium?", pr: "MAHG-nah oh PREH-mee-oom" },
  { cat: "gas", topic: "fill", kind: "hear", es: "Está en ceros, joven.", en: "It's at zero.", pr: "ehs-TAH ehn SEH-rohs, HOH-vehn", note: "Joven, güero and jefe are friendly ways attendants address you." },
  { cat: "gas", topic: "fill", kind: "hear", es: "¿Me abre el tanque?", en: "Can you open the gas cap?", pr: "meh AH-breh ehl TAHN-keh", note: "They want you to pop the fuel door from inside." },
  { cat: "gas", topic: "fill", kind: "hear", es: "Ya quedó.", en: "All done.", pr: "yah keh-DOH" },

  // Paying & avoiding scams
  { cat: "gas", topic: "pay", es: "¿Puedo pagar con tarjeta aquí en la bomba?", en: "Can I pay by card here at the pump?", pr: "PWEH-doh pah-GAR kohn tar-HEH-tah ah-KEE ehn lah BOHM-bah" },
  { cat: "gas", topic: "pay", es: "Voy a pagar con tarjeta.", en: "I'll pay by card.", pr: "voy ah pah-GAR kohn tar-HEH-tah", note: "They bring the terminal to your window. Keep your card where you can see it." },
  { cat: "gas", topic: "pay", es: "En efectivo.", en: "Cash.", pr: "ehn eh-fehk-TEE-voh" },
  { cat: "gas", topic: "pay", es: "Aquí tiene quinientos.", en: "Here's 500.", pr: "ah-KEE tee-EH-neh kee-nee-EHN-tohs", note: "Say the amount out loud as you hand it over. It stops the bill-swap trick." },
  { cat: "gas", topic: "pay", es: "Le di un billete de quinientos.", en: "I gave you a 500 bill.", pr: "leh dee oon bee-YEH-teh deh kee-nee-EHN-tohs", note: "The classic scam is swapping your 500 for a 50 and saying you underpaid. Stand firm." },
  { cat: "gas", topic: "pay", es: "¿Me da mi cambio, por favor?", en: "May I have my change, please?", pr: "meh dah mee KAHM-bee-oh, por fah-VOR" },
  { cat: "gas", topic: "pay", es: "Me cobró de más.", en: "You charged me too much.", pr: "meh koh-BROH deh MAHS" },
  { cat: "gas", topic: "pay", es: "¿Me da un ticket?", en: "Can I have a receipt?", pr: "meh dah oon TEE-keht" },
  { cat: "gas", topic: "pay", es: "Esto es para usted.", en: "This is for you.", pr: "EHS-toh ehs PAH-rah oos-TEHD", note: "Tip the attendant 10–20 pesos, a little more if they cleaned the windshield or checked the tires." },
  { cat: "gas", topic: "pay", kind: "hear", es: "¿Efectivo o tarjeta?", en: "Cash or card?", pr: "eh-fehk-TEE-voh oh tar-HEH-tah" },
  { cat: "gas", topic: "pay", kind: "hear", es: "¿Crédito o débito?", en: "Credit or debit?", pr: "KREH-dee-toh oh DEH-bee-toh" },
  { cat: "gas", topic: "pay", kind: "hear", es: "Su NIP, por favor.", en: "Your PIN, please.", pr: "soo neep, por fah-VOR", note: "NIP is Mexican for PIN." },
  { cat: "gas", topic: "pay", kind: "hear", es: "¿Requiere factura?", en: "Do you need a tax invoice?", pr: "reh-kee-EH-reh fahk-TOO-rah", note: "A factura is an official invoice for businesses. Just say \"No, gracias.\"" },
  { cat: "gas", topic: "pay", kind: "hear", es: "Le faltan cien.", en: "You're 100 short.", pr: "leh FAHL-tahn see-EHN", note: "If you know what you handed over, say so: \"Le di quinientos.\"" },

  // Air, oil & windshield
  { cat: "gas", topic: "service", es: "¿Me revisa el aire de las llantas?", en: "Can you check the tire pressure?", pr: "meh reh-VEE-sah ehl EYE-reh deh lahs YAHN-tahs" },
  { cat: "gas", topic: "service", es: "¿Dónde hay aire?", en: "Where's the air pump?", pr: "DOHN-deh eye EYE-reh" },
  { cat: "gas", topic: "service", es: "Treinta y dos libras, por favor.", en: "32 PSI, please.", pr: "TRAYN-tah ee dohs LEE-brahs, por fah-VOR", note: "Tire pressure is given in libras (pounds)." },
  { cat: "gas", topic: "service", es: "¿Me checa el aceite?", en: "Can you check the oil?", pr: "meh CHEH-kah ehl ah-SAY-teh" },
  { cat: "gas", topic: "service", es: "¿Me limpia el parabrisas?", en: "Can you clean the windshield?", pr: "meh LEEM-pee-ah ehl pah-rah-BREE-sahs" },
  { cat: "gas", topic: "service", es: "¿Tienen agua para el radiador?", en: "Do you have water for the radiator?", pr: "tee-EH-nehn AH-gwah PAH-rah ehl rah-dee-ah-DOR" },
  { cat: "gas", topic: "service", es: "No, gracias, así está bien.", en: "No thanks, it's fine as is.", pr: "noh GRAH-see-ahs, ah-SEE ehs-TAH bee-EHN" },
  { cat: "gas", topic: "service", kind: "hear", es: "¿Le checo el aceite?", en: "Shall I check your oil?", pr: "leh CHEH-koh ehl ah-SAY-teh" },
  { cat: "gas", topic: "service", kind: "hear", es: "¿Le limpio el parabrisas?", en: "Shall I clean your windshield?", pr: "leh LEEM-pee-oh ehl pah-rah-BREE-sahs" },
  { cat: "gas", topic: "service", kind: "hear", es: "Le falta aceite.", en: "You're low on oil.", pr: "leh FAHL-tah ah-SAY-teh", note: "Sometimes true, sometimes an upsell. \"Ahorita no, gracias\" means not right now." },
  { cat: "gas", topic: "service", kind: "hear", es: "Trae baja la llanta.", en: "Your tire is low.", pr: "TRAH-eh BAH-hah lah YAHN-tah" },

  // Car trouble
  { cat: "gas", topic: "trouble", es: "Se me ponchó una llanta.", en: "I got a flat tire.", pr: "seh meh pohn-CHOH OO-nah YAHN-tah" },
  { cat: "gas", topic: "trouble", es: "¿Dónde hay una vulcanizadora?", en: "Where's a tire repair shop?", pr: "DOHN-deh eye OO-nah vool-kah-nee-sah-DOH-rah", note: "Also called a llantera. Look for tires painted on a roadside wall." },
  { cat: "gas", topic: "trouble", es: "¿Hay un mecánico cerca?", en: "Is there a mechanic nearby?", pr: "eye oon meh-KAH-nee-koh SEHR-kah" },
  { cat: "gas", topic: "trouble", es: "El coche no arranca.", en: "The car won't start.", pr: "ehl KOH-cheh noh ah-RRAHN-kah" },
  { cat: "gas", topic: "trouble", es: "Se quedó sin batería.", en: "The battery is dead.", pr: "seh keh-DOH seen bah-teh-REE-ah" },
  { cat: "gas", topic: "trouble", es: "¿Me puede pasar corriente?", en: "Can you give me a jump start?", pr: "meh PWEH-deh pah-SAR koh-rree-EHN-teh" },
  { cat: "gas", topic: "trouble", es: "Se prendió una luz en el tablero.", en: "A warning light came on.", pr: "seh prehn-dee-OH OO-nah loos ehn ehl tah-BLEH-roh" },
  { cat: "gas", topic: "trouble", es: "Se está calentando el motor.", en: "The engine is overheating.", pr: "seh ehs-TAH kah-lehn-TAHN-doh ehl moh-TOR" },
  { cat: "gas", topic: "trouble", es: "Está tirando aceite.", en: "It's leaking oil.", pr: "ehs-TAH tee-RAHN-doh ah-SAY-teh" },
  { cat: "gas", topic: "trouble", es: "¿Cuánto cuesta arreglarlo?", en: "How much to fix it?", pr: "KWAHN-toh KWEHS-tah ah-rreh-GLAR-loh" },
  { cat: "gas", topic: "trouble", es: "¿Para cuándo queda?", en: "When will it be ready?", pr: "PAH-rah KWAHN-doh KEH-dah" },
  { cat: "gas", topic: "trouble", kind: "hear", es: "Hay que cambiarla.", en: "It needs to be replaced.", pr: "eye keh kahm-bee-AR-lah" },
  { cat: "gas", topic: "trouble", kind: "hear", es: "Queda en una hora.", en: "It'll be ready in an hour.", pr: "KEH-dah ehn OO-nah OH-rah" },

  // The road ahead
  { cat: "gas", topic: "road", es: "¿Hay otra gasolinera más adelante?", en: "Is there another gas station further on?", pr: "eye OH-trah gah-soh-lee-NEH-rah mahs ah-deh-LAHN-teh" },
  { cat: "gas", topic: "road", es: "¿Qué tan lejos está la siguiente?", en: "How far is the next one?", pr: "keh tahn LEH-hohs ehs-TAH lah see-gee-EHN-teh" },
  { cat: "gas", topic: "road", es: "¿Cómo regreso a la carretera?", en: "How do I get back to the highway?", pr: "KOH-moh reh-GREH-soh ah lah kah-rreh-TEH-rah" },
  { cat: "gas", topic: "road", es: "¿Esta es la libre o la cuota?", en: "Is this the free road or the toll road?", pr: "EHS-tah ehs lah LEE-breh oh lah KWOH-tah", note: "Cuota = toll highway, faster and safer. Libre = free road through the towns." },
  { cat: "gas", topic: "road", es: "¿Cuánto cuesta la caseta?", en: "How much is the toll booth?", pr: "KWAHN-toh KWEHS-tah lah kah-SEH-tah" },
  { cat: "gas", topic: "road", es: "¿Es seguro manejar de noche por aquí?", en: "Is it safe to drive around here at night?", pr: "ehs seh-GOO-roh mah-neh-HAR deh NOH-cheh por ah-KEE" },
  { cat: "gas", topic: "road", kind: "hear", es: "Aguas con los topes.", en: "Watch out for the speed bumps.", pr: "AH-gwahs kohn lohs TOH-pehs", note: "\"¡Aguas!\" means watch out. Topes are everywhere, often unpainted." },
  { cat: "gas", topic: "road", kind: "hear", es: "Está a unos veinte kilómetros.", en: "It's about 20 kilometers away.", pr: "ehs-TAH ah OO-nohs VAYN-teh kee-LOH-meh-trohs" },
  { cat: "gas", topic: "road", kind: "hear", es: "Siga derecho hasta el retorno.", en: "Keep going straight to the U-turn.", pr: "SEE-gah deh-REH-choh AHS-tah ehl reh-TOR-noh", note: "On divided highways you often pass your turn and come back at a retorno." },

  // Restroom & snacks
  { cat: "gas", topic: "stop", es: "¿Tienen baño?", en: "Do you have a restroom?", pr: "tee-EH-nehn BAH-nyoh", note: "Gas station restrooms often cost 5–10 pesos. Carry coins." },
  { cat: "gas", topic: "stop", es: "¿Cuánto cuesta el baño?", en: "How much is the restroom?", pr: "KWAHN-toh KWEHS-tah ehl BAH-nyoh" },
  { cat: "gas", topic: "stop", es: "¿Hay papel?", en: "Is there toilet paper?", pr: "eye pah-PEHL", note: "Sometimes the attendant hands you paper when you pay." },
  { cat: "gas", topic: "stop", es: "¿Venden hielo?", en: "Do you sell ice?", pr: "VEHN-dehn YEH-loh" },
  { cat: "gas", topic: "stop", es: "Una botella de agua, por favor.", en: "A bottle of water, please.", pr: "OO-nah boh-TEH-yah deh AH-gwah, por fah-VOR" },
  { cat: "gas", topic: "stop", kind: "hear", es: "Son cinco pesos.", en: "It's five pesos.", pr: "sohn SEEN-koh PEH-sohs" },
  { cat: "gas", topic: "stop", kind: "hear", es: "El baño está cerrado.", en: "The restroom is closed.", pr: "ehl BAH-nyoh ehs-TAH seh-RRAH-doh" },

  // Car words
  { cat: "gas", topic: "car", kind: "word", es: "la gasolinera", en: "gas station", pr: "lah gah-soh-lee-NEH-rah" },
  { cat: "gas", topic: "car", kind: "word", es: "la bomba", en: "pump", pr: "lah BOHM-bah" },
  { cat: "gas", topic: "car", kind: "word", es: "el litro", en: "liter", pr: "ehl LEE-troh", note: "Gas is sold by the liter. A gallon is about 3.8 liters." },
  { cat: "gas", topic: "car", kind: "word", es: "el tanque", en: "gas tank", pr: "ehl TAHN-keh" },
  { cat: "gas", topic: "car", kind: "word", es: "la llanta", en: "tire", pr: "lah YAHN-tah" },
  { cat: "gas", topic: "car", kind: "word", es: "el aceite", en: "oil", pr: "ehl ah-SAY-teh" },
  { cat: "gas", topic: "car", kind: "word", es: "el cofre", en: "hood", pr: "ehl KOH-freh" },
  { cat: "gas", topic: "car", kind: "word", es: "la cajuela", en: "trunk", pr: "lah kah-HWEH-lah" },
  { cat: "gas", topic: "car", kind: "word", es: "los frenos", en: "brakes", pr: "lohs FREH-nohs" },
  { cat: "gas", topic: "car", kind: "word", es: "la batería", en: "battery", pr: "lah bah-teh-REE-ah" },
  { cat: "gas", topic: "car", kind: "word", es: "las llaves", en: "keys", pr: "lahs YAH-vehs" },
  { cat: "gas", topic: "car", kind: "word", es: "el tope", en: "speed bump", pr: "ehl TOH-peh" },
  { cat: "gas", topic: "car", kind: "word", es: "la caseta", en: "toll booth", pr: "lah kah-SEH-tah" },
  { cat: "gas", topic: "car", kind: "word", es: "la desviación", en: "detour", pr: "lah dehs-vee-ah-see-OHN" },
];
