// es = Spanish, en = English, pr = pronunciation for English speakers (CAPS = stressed syllable), note = optional tip
const CATEGORIES = [
  { id: "daily", name: "Everyday", es: "Diario", icon: "👋" },
  { id: "food", name: "Restaurants", es: "Restaurante", icon: "🌮" },
  { id: "store", name: "Stores", es: "Tienda", icon: "🛍️" },
];

const PHRASES = [
  // ---------- Everyday ----------
  { cat: "daily", es: "Hola", en: "Hello", pr: "OH-lah" },
  { cat: "daily", es: "Buenos días", en: "Good morning", pr: "BWEH-nohs DEE-ahs", note: "Use until about noon. Greeting people when you walk into a small shop or elevator is expected." },
  { cat: "daily", es: "Buenas tardes", en: "Good afternoon", pr: "BWEH-nahs TAR-dehs", note: "From noon until dark." },
  { cat: "daily", es: "Buenas noches", en: "Good evening / Good night", pr: "BWEH-nahs NOH-chehs", note: "Used both as a greeting after dark and as goodbye." },
  { cat: "daily", es: "¿Qué tal?", en: "How's it going?", pr: "keh TAHL" },
  { cat: "daily", es: "¿Cómo está?", en: "How are you? (polite)", pr: "KOH-moh ehs-TAH", note: "Formal \"usted\" form. Use it with strangers, older people and staff." },
  { cat: "daily", es: "¿Cómo estás?", en: "How are you? (casual)", pr: "KOH-moh ehs-TAHS", note: "Informal \"tú\" form, for friends and people your age." },
  { cat: "daily", es: "Bien, gracias. ¿Y usted?", en: "Good, thanks. And you?", pr: "bee-EHN GRAH-see-ahs. ee oos-TEHD" },
  { cat: "daily", es: "Mucho gusto", en: "Nice to meet you", pr: "MOO-choh GOOS-toh" },
  { cat: "daily", es: "Me llamo…", en: "My name is…", pr: "meh YAH-moh" },
  { cat: "daily", es: "Por favor", en: "Please", pr: "por fah-VOR" },
  { cat: "daily", es: "Muchas gracias", en: "Thank you very much", pr: "MOO-chahs GRAH-see-ahs" },
  { cat: "daily", es: "De nada", en: "You're welcome", pr: "deh NAH-dah", note: "You'll also hear \"a la orden\" (at your service) and \"para servirle\"." },
  { cat: "daily", es: "Con permiso", en: "Excuse me (to get past someone)", pr: "kohn pehr-MEE-soh", note: "Also said when leaving a table or a room." },
  { cat: "daily", es: "Disculpe", en: "Excuse me / Sorry (to get attention)", pr: "dees-KOOL-peh" },
  { cat: "daily", es: "Perdón", en: "Sorry / Pardon me", pr: "pehr-DOHN" },
  { cat: "daily", es: "¿Mande?", en: "Pardon? / Sorry, what?", pr: "MAHN-deh", note: "The polite Mexican way to ask someone to repeat. Much nicer than \"¿Qué?\"." },
  { cat: "daily", es: "Sale", en: "OK / Deal (casual)", pr: "SAH-leh", note: "Very Mexican. \"Va\" and \"órale\" work the same way." },
  { cat: "daily", es: "No entiendo", en: "I don't understand", pr: "noh ehn-tee-EHN-doh" },
  { cat: "daily", es: "¿Habla inglés?", en: "Do you speak English?", pr: "AH-blah een-GLEHS" },
  { cat: "daily", es: "Hablo un poco de español", en: "I speak a little Spanish", pr: "AH-bloh oon POH-koh deh ehs-pah-NYOHL" },
  { cat: "daily", es: "¿Puede hablar más despacio?", en: "Can you speak more slowly?", pr: "PWEH-deh ah-BLAR mahs dehs-PAH-see-oh" },
  { cat: "daily", es: "¿Cómo se dice … en español?", en: "How do you say … in Spanish?", pr: "KOH-moh seh DEE-seh … ehn ehs-pah-NYOHL" },
  { cat: "daily", es: "¿Dónde está el baño?", en: "Where is the bathroom?", pr: "DOHN-deh ehs-TAH ehl BAH-nyoh", note: "Public restrooms often cost 5–10 pesos. Keep coins handy." },
  { cat: "daily", es: "¿Dónde está…?", en: "Where is…?", pr: "DOHN-deh ehs-TAH" },
  { cat: "daily", es: "¿Está lejos?", en: "Is it far?", pr: "ehs-TAH LEH-hohs" },
  { cat: "daily", es: "A la derecha / a la izquierda", en: "To the right / to the left", pr: "ah lah deh-REH-chah / ah lah ees-kee-EHR-dah" },
  { cat: "daily", es: "Todo derecho", en: "Straight ahead", pr: "TOH-doh deh-REH-choh" },
  { cat: "daily", es: "¿Cuánto cuesta ir a…?", en: "How much to go to…? (taxi)", pr: "KWAHN-toh KWEHS-tah eer ah", note: "Agree on the fare before you get in if there's no meter." },
  { cat: "daily", es: "¿Qué hora es?", en: "What time is it?", pr: "keh OH-rah ehs" },
  { cat: "daily", es: "Ahorita", en: "Right now / In a little bit", pr: "ah-oh-REE-tah", note: "Famously flexible: can mean this second, in an hour, or maybe never." },
  { cat: "daily", es: "¿Me puede ayudar?", en: "Can you help me?", pr: "meh PWEH-deh ah-yoo-DAR" },
  { cat: "daily", es: "Estoy perdido / perdida", en: "I'm lost (man / woman)", pr: "ehs-TOY pehr-DEE-doh / pehr-DEE-dah" },
  { cat: "daily", es: "¿Hay wifi? ¿Cuál es la contraseña?", en: "Is there wifi? What's the password?", pr: "eye WEE-fee? kwahl ehs lah kohn-trah-SEH-nyah" },
  { cat: "daily", es: "¿Nos puede tomar una foto?", en: "Could you take a photo of us?", pr: "nohs PWEH-deh toh-MAR OO-nah FOH-toh" },
  { cat: "daily", es: "No hay problema", en: "No problem", pr: "noh eye proh-BLEH-mah" },
  { cat: "daily", es: "¿Qué onda?", en: "What's up? (casual)", pr: "keh OHN-dah" },
  { cat: "daily", es: "¡Qué padre!", en: "How cool! / Awesome!", pr: "keh PAH-dreh" },
  { cat: "daily", es: "Nos vemos", en: "See you", pr: "nohs VEH-mohs" },
  { cat: "daily", es: "Hasta luego", en: "See you later / Bye", pr: "AHS-tah LWEH-goh" },
  { cat: "daily", es: "¡Que le vaya bien!", en: "Have a good one! (lit. may it go well)", pr: "keh leh VAH-yah bee-EHN" },

  // ---------- Restaurants ----------
  { cat: "food", es: "Una mesa para dos, por favor", en: "A table for two, please", pr: "OO-nah MEH-sah PAH-rah dohs, por fah-VOR", note: "tres = 3, cuatro = 4, cinco = 5" },
  { cat: "food", es: "Tengo una reservación a nombre de…", en: "I have a reservation under the name…", pr: "TEHN-goh OO-nah reh-sehr-vah-see-OHN ah NOHM-breh deh" },
  { cat: "food", es: "¿Tiene mesa afuera?", en: "Do you have a table outside?", pr: "tee-EH-neh MEH-sah ah-FWEH-rah" },
  { cat: "food", es: "La carta, por favor", en: "The menu, please", pr: "lah KAR-tah, por fah-VOR", note: "\"El menú\" is also understood. \"Menú del día\" / \"comida corrida\" is a cheap set lunch." },
  { cat: "food", es: "Joven / Señorita", en: "Excuse me (to call the waiter / waitress)", pr: "HOH-vehn / seh-nyoh-REE-tah", note: "\"Joven\" (young man) is used for male servers of any age. Never snap or whistle." },
  { cat: "food", es: "¿Qué me recomienda?", en: "What do you recommend?", pr: "keh meh reh-koh-mee-EHN-dah" },
  { cat: "food", es: "¿Cuál es la especialidad de la casa?", en: "What's the house specialty?", pr: "kwahl ehs lah ehs-peh-see-ah-lee-DAHD deh lah KAH-sah" },
  { cat: "food", es: "Quisiera…", en: "I would like…", pr: "kee-see-EH-rah" },
  { cat: "food", es: "Me da…, por favor", en: "I'll have…, please (lit. give me)", pr: "meh DAH…, por fah-VOR", note: "Sounds blunt in English but is completely normal and polite in Mexico." },
  { cat: "food", es: "¿Me regala una servilleta?", en: "Could I get a napkin?", pr: "meh reh-GAH-lah OO-nah sehr-vee-YEH-tah", note: "\"Regalar\" literally means to gift, but Mexicans use it as a soft, polite \"may I have\"." },
  { cat: "food", es: "¿Me trae…?", en: "Could you bring me…?", pr: "meh TRAH-eh" },
  { cat: "food", es: "Para mí…", en: "For me…", pr: "PAH-rah MEE" },
  { cat: "food", es: "Para aquí", en: "For here (dine in)", pr: "PAH-rah ah-KEE" },
  { cat: "food", es: "Para llevar", en: "To go", pr: "PAH-rah yeh-VAR" },
  { cat: "food", es: "¿De qué tiene?", en: "What fillings do you have? (tacos, tamales…)", pr: "deh KEH tee-EH-neh" },
  { cat: "food", es: "Dos tacos al pastor, por favor", en: "Two al pastor tacos, please", pr: "dohs TAH-kohs ahl pahs-TOR", note: "Al pastor = spit-roasted marinated pork, often with pineapple." },
  { cat: "food", es: "Con todo", en: "With everything", pr: "kohn TOH-doh", note: "On tacos this usually means onion and cilantro." },
  { cat: "food", es: "Sin cebolla", en: "Without onion", pr: "seen seh-BOH-yah" },
  { cat: "food", es: "¿Pica?", en: "Is it spicy?", pr: "PEE-kah", note: "If they say \"poquito\" (a little), assume it's spicy." },
  { cat: "food", es: "Que no pique, por favor", en: "Not spicy, please", pr: "keh noh PEE-keh, por fah-VOR" },
  { cat: "food", es: "La salsa aparte, por favor", en: "Sauce on the side, please", pr: "lah SAHL-sah ah-PAR-teh" },
  { cat: "food", es: "Soy alérgico / alérgica a…", en: "I'm allergic to… (man / woman)", pr: "soy ah-LEHR-hee-koh / ah-LEHR-hee-kah ah", note: "cacahuate = peanut, mariscos = shellfish, nueces = nuts, lácteos = dairy, gluten = gluten" },
  { cat: "food", es: "Soy vegetariano / vegetariana", en: "I'm vegetarian (man / woman)", pr: "soy veh-heh-tah-ree-AH-noh" },
  { cat: "food", es: "¿Tiene carne?", en: "Does it have meat?", pr: "tee-EH-neh KAR-neh", note: "Some people don't count chicken or ham as \"carne\". Ask about each: pollo, jamón, manteca (lard)." },
  { cat: "food", es: "¿Las quesadillas llevan queso?", en: "Do the quesadillas come with cheese?", pr: "lahs keh-sah-DEE-yahs YEH-vahn KEH-soh", note: "In Mexico City they often don't unless you ask!" },
  { cat: "food", es: "Una cerveza, por favor", en: "A beer, please", pr: "OO-nah sehr-VEH-sah", note: "Ask \"¿Cuáles tiene?\" to hear what beers they have." },
  { cat: "food", es: "Una michelada", en: "A michelada (beer with lime and salt, often spicy sauces)", pr: "OO-nah mee-cheh-LAH-dah", note: "A \"chelada\" is just beer, lime and salt, with no sauces." },
  { cat: "food", es: "Un agua natural", en: "A still water", pr: "oon AH-gwah nah-too-RAHL", note: "\"Agua mineral\" is sparkling. \"Agua fresca\" is a fruit drink (jamaica, horchata, tamarindo)." },
  { cat: "food", es: "¿El agua es purificada?", en: "Is the water purified?", pr: "ehl AH-gwah ehs poo-ree-fee-KAH-dah", note: "Don't drink tap water. Restaurant ice is normally made from purified water." },
  { cat: "food", es: "Sin hielo", en: "No ice", pr: "seen YEH-loh" },
  { cat: "food", es: "Un café con leche", en: "A coffee with milk", pr: "oon kah-FEH kohn LEH-cheh", note: "\"Café de olla\" is sweet, cinnamon-spiced coffee. Worth trying." },
  { cat: "food", es: "Otra, por favor", en: "Another one, please", pr: "OH-trah, por fah-VOR", note: "Use \"otro\" for a masculine thing (otro café, otro taco)." },
  { cat: "food", es: "Todo bien, gracias", en: "Everything's good, thanks", pr: "TOH-doh bee-EHN, GRAH-see-ahs" },
  { cat: "food", es: "¡Está muy rico!", en: "It's delicious!", pr: "ehs-TAH mooy REE-koh" },
  { cat: "food", es: "¡Provecho!", en: "Enjoy your meal!", pr: "proh-VEH-choh", note: "Mexicans say it to other diners when passing their table or leaving the restaurant." },
  { cat: "food", es: "La cuenta, por favor", en: "The check, please", pr: "lah KWEHN-tah, por fah-VOR", note: "It won't come until you ask. You can also mime signing in the air." },
  { cat: "food", es: "¿Aceptan tarjeta?", en: "Do you take cards?", pr: "ah-SEHP-tahn tar-HEH-tah", note: "Many taquerías and markets are cash only." },
  { cat: "food", es: "¿Me trae la terminal?", en: "Can you bring the card machine?", pr: "meh TRAH-eh lah tehr-mee-NAHL", note: "The card reader comes to your table. Your card shouldn't leave your sight." },
  { cat: "food", es: "¿Está incluida la propina?", en: "Is the tip included?", pr: "ehs-TAH een-kloo-EE-dah lah proh-PEE-nah", note: "10–15% is standard at sit-down restaurants. Check the bill for \"servicio incluido\"." },
  { cat: "food", es: "¿Podemos pagar por separado?", en: "Can we pay separately?", pr: "poh-DEH-mohs pah-GAR por seh-pah-RAH-doh" },
  { cat: "food", es: "¿Dónde se paga?", en: "Where do I pay?", pr: "DOHN-deh seh PAH-gah", note: "At street stalls you usually pay at the end. Tell them what you ate." },

  // ---------- Stores ----------
  { cat: "store", es: "¿Cuánto cuesta?", en: "How much does it cost?", pr: "KWAHN-toh KWEHS-tah" },
  { cat: "store", es: "¿Cuánto es?", en: "How much is it? (total)", pr: "KWAHN-toh EHS" },
  { cat: "store", es: "¿Cuánto le debo?", en: "What do I owe you?", pr: "KWAHN-toh leh DEH-boh" },
  { cat: "store", es: "Son ciento cincuenta pesos", en: "That's 150 pesos", pr: "sohn see-EHN-toh seen-KWEHN-tah PEH-sohs", note: "20 veinte · 50 cincuenta · 100 cien · 200 doscientos · 500 quinientos · 1,000 mil" },
  { cat: "store", es: "¿Tiene…?", en: "Do you have…?", pr: "tee-EH-neh" },
  { cat: "store", es: "Estoy buscando…", en: "I'm looking for…", pr: "ehs-TOY boos-KAHN-doh" },
  { cat: "store", es: "¿Dónde encuentro…?", en: "Where can I find…?", pr: "DOHN-deh ehn-KWEHN-troh" },
  { cat: "store", es: "Solo estoy viendo, gracias", en: "I'm just looking, thanks", pr: "SOH-loh ehs-TOY vee-EHN-doh, GRAH-see-ahs" },
  { cat: "store", es: "¿Me lo puedo probar?", en: "Can I try it on?", pr: "meh loh PWEH-doh proh-BAR" },
  { cat: "store", es: "¿Tiene otra talla?", en: "Do you have another size?", pr: "tee-EH-neh OH-trah TAH-yah" },
  { cat: "store", es: "Más grande / más chico", en: "Bigger / smaller", pr: "mahs GRAHN-deh / mahs CHEE-koh", note: "Mexico says \"chico\" far more than \"pequeño\"." },
  { cat: "store", es: "¿Lo tiene en otro color?", en: "Do you have it in another color?", pr: "loh tee-EH-neh ehn OH-troh koh-LOR" },
  { cat: "store", es: "Me lo llevo", en: "I'll take it", pr: "meh loh YEH-voh", note: "\"Me la llevo\" for a feminine thing (la camisa, la bolsa)." },
  { cat: "store", es: "Está muy caro", en: "It's very expensive", pr: "ehs-TAH mooy KAH-roh" },
  { cat: "store", es: "¿Me hace un descuento?", en: "Can you give me a discount?", pr: "meh AH-seh oon dehs-KWEHN-toh", note: "Fine at markets and with street vendors. Not in chain stores or supermarkets." },
  { cat: "store", es: "¿Es lo menos?", en: "Is that your best price?", pr: "ehs loh MEH-nohs", note: "The classic market bargaining line. Keep it friendly." },
  { cat: "store", es: "¿Puedo pagar con tarjeta?", en: "Can I pay by card?", pr: "PWEH-doh pah-GAR kohn tar-HEH-tah" },
  { cat: "store", es: "Solo efectivo", en: "Cash only", pr: "SOH-loh eh-fehk-TEE-voh", note: "A sign you'll see often." },
  { cat: "store", es: "¿Aceptan dólares?", en: "Do you accept dollars?", pr: "ah-SEHP-tahn DOH-lah-rehs", note: "Paying in pesos almost always gets you a better rate." },
  { cat: "store", es: "¿Tiene cambio de quinientos?", en: "Do you have change for a 500?", pr: "tee-EH-neh KAHM-bee-oh deh kee-nee-EHN-tohs", note: "Small shops and taxis often can't break big bills. Carry 20s, 50s and coins." },
  { cat: "store", es: "No traigo cambio", en: "I don't have change / small bills", pr: "noh TRY-goh KAHM-bee-oh", note: "You'll also hear \"feria\", Mexican slang for small change." },
  { cat: "store", es: "¿Me cobra, por favor?", en: "Can you ring me up, please?", pr: "meh KOH-brah, por fah-VOR" },
  { cat: "store", es: "¿Algo más?", en: "Anything else?", pr: "AHL-goh MAHS", note: "You'll hear this at every register." },
  { cat: "store", es: "Es todo, gracias", en: "That's all, thanks", pr: "ehs TOH-doh, GRAH-see-ahs" },
  { cat: "store", es: "¿Redondea?", en: "Would you like to round up? (to donate)", pr: "reh-dohn-DEH-ah", note: "Cashiers at OXXO and supermarkets ask this. \"No, gracias\" is perfectly fine." },
  { cat: "store", es: "¿Me da una bolsa?", en: "Can I have a bag?", pr: "meh DAH OO-nah BOHL-sah", note: "Many states ban free plastic bags, so bring your own tote." },
  { cat: "store", es: "No necesito bolsa, gracias", en: "I don't need a bag, thanks", pr: "noh neh-seh-SEE-toh BOHL-sah" },
  { cat: "store", es: "¿Me da el ticket?", en: "Can I have the receipt?", pr: "meh DAH ehl TEE-keht", note: "\"Ticket\" is the everyday word for a receipt." },
  { cat: "store", es: "Un kilo de…, por favor", en: "A kilo of…, please", pr: "oon KEE-loh deh", note: "Produce and meat are sold by the kilo (about 2.2 lb). \"Medio kilo\" = half, \"un cuarto\" = a quarter." },
  { cat: "store", es: "¿Está fresco?", en: "Is it fresh?", pr: "ehs-TAH FREHS-koh" },
  { cat: "store", es: "¿Tiene algo para…?", en: "Do you have something for…? (pharmacy)", pr: "tee-EH-neh AHL-goh PAH-rah", note: "…el dolor de cabeza (headache), …la diarrea, …las quemaduras de sol (sunburn), …la tos (cough)" },
  { cat: "store", es: "Una recarga de cien pesos, por favor", en: "A 100-peso phone top-up, please", pr: "OO-nah reh-KAR-gah deh see-EHN PEH-sohs", note: "Top up prepaid SIMs (Telcel, AT&T) at any OXXO. Tell them the carrier and your number." },
  { cat: "store", es: "¿Dónde hay un cajero?", en: "Where is there an ATM?", pr: "DOHN-deh eye oon kah-HEH-roh", note: "Use ATMs inside bank branches. Decline the ATM's own currency conversion." },
  { cat: "store", es: "¿A qué hora cierran?", en: "What time do you close?", pr: "ah keh OH-rah see-EH-rrahn", note: "\"¿A qué hora abren?\" = What time do you open?" },
  { cat: "store", es: "¿Me lo envuelve para regalo?", en: "Can you gift-wrap it?", pr: "meh loh ehn-VWEHL-veh PAH-rah reh-GAH-loh" },
];
