// Rebuild vocab.js from phrases.js. Run from this directory: node make_vocab.cjs
// Same prompt as tools/voice-eval/run_whisper.py: kind "word" entries, articles dropped, first 600 chars.
const fs = require("fs");
const src = fs.readFileSync(__dirname + "/../../phrases.js", "utf8").replace(/^const /gm, "var ");
const PHRASES = new Function(src + "; return PHRASES;")();
const words = [...new Set(PHRASES.filter((p) => p.kind === "word").flatMap((p) => p.es.split(" / ")).map((w) => w.replace(/^(el|la|los|las) /, "")))];
const s = ("Vocabulario: " + words.join(", ")).slice(0, 600);
fs.writeFileSync(__dirname + "/vocab.js",
  "// Generated by make_vocab.cjs from phrases.js: the Whisper initial_prompt measured in SCOPE §2 (turbo + prompt).\n" +
  "export const VOCAB_ES = " + JSON.stringify(s) + ";\n");
